### ISSUE TITLE
Opera player bug

### ISSUE THREAD

**Issue by maydin** [ant-media/Ant-Media-Server#1650]
When user plays a webrtc stream in windows and opera, it doesnt play. A spinner is displayed but video doesnt start.
Tried in parallels windows 10-latest version of opera.
User can publish video in opera and it could be watched in another browser, for ex: mobile android browser.
Tried with flowplayer, didnt work either.
"user interaction needed" log is logged in player.html
disabled autoplay and used play button click to trigger video play, didnt work either.

**Comment by ggassmann** [comment]
I can confirm this is occurring in Amaz
[web console log opera issue.txt](https://github.com/ant-media/Ant-Media-Server/files/4506315/web.console.log.opera.issue.txt)
on AMI Enterprise Edition 1.9.1 20200112_1830.

**Comment by eneskuluk** [comment]
Opera does not come with a native support of h.264. It's dependent on the environment that it is installed. Opera supports VP8,VP9, AV1 natively but not h.264. This is because proprietary licence issues of h.264 .
To use h.264 in opera in a Windows 10 environment, Windows Media Pack needs to be installed.
On the other hand, VP8 can be used to stream which work flawless with Opera.
Disabling h.264 and enabling vp8 in Ant Media Settings would solve this issue.
