### ISSUE TITLE
Which companies are developing health software?

### ISSUE THREAD

**Issue by MarkMorris1992** [ant-media/Ant-Media-Server#1769]
Which companies are developing health software?

**Comment by SelimEmre** [comment]
Your question is not clear. Can you please more clear about your issue?

**Comment by Henrywallen** [comment]
Good service at a reasonable cost. We didn’t have to help them figure out Healthcare because they already know how Healthcare software  works and which aspects are necessary for this industry. If you are looking for a professional software development team, I highly recommend Inoxoft [https://inoxoft.com/industries/healthcare/](https://inoxoft.com/industries/healthcare/).

**Comment by mekya** [comment]
Closing this issue. Please re-open it if you have a question
