### ISSUE TITLE
start.bat missing !!!

### ISSUE THREAD

**Issue by dinihou** [ant-media/Ant-Media-Server#19]
hi, i try run on windows server but don't found start.bat
try of 1.1.0 but error and exit

**Comment by mekya** [comment]
Hi @dinihou ,

Unfourtunately, latest version 1.2.0 does not support Windows. Because building native libraries for windows is very hard and the result is very unstable for us so Ant Media Server runs on Linux and Mac system. 

I am closing this issue, please let me know if you have any question.

Sorry :(

**Comment by dinihou** [comment]
I will change to linux
Thanks
