### ISSUE TITLE
Low quality streaming when screen share

### ISSUE THREAD

**Issue by MinhHungTrinh** [ant-media/Ant-Media-Server#1959]
# Issue
Low quality streaming when screen share
### Short description
When I share my screen and publish streaming. The video quality doesn't look as sharp as it should be. It's like downscaling the quality to lesser HD.

### Environment
Community edition
* Operating system and version:
* Java version: JDK-11
* Ant Media Server version: lastest
* Browser name and version: Chrome Version 80.0.3987.132 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by canat** [comment]
Hello,
We need more information to identify the problem. Screen sharing works on my 2560x1440 resolution monitor without any quality problems.
What is your screen resolution?  
Normally, the Ant Media Server does not downscale the screen video captured by the browser unless otherwise specified. 
Is the quality of the captured video directly after selecting screen share option also bad? Or only the quality of the published video of the screen share after playing it, is bad? 
Can you send us screenshot of the screen published with Ant Media Server which has a bad quality?

Best Regards,
Can

**Comment by Hung-TM** [comment]
Oh. I try with **community** edition. And only the quality of the published video of the screen share after playing it.
But I try with **enterprise** edition.  Everythings are good. The video quality is not downscale. This problem resolved.
Thank you for reply!
