### ISSUE TITLE
concurrent 6 video viewers

### ISSUE THREAD

**Issue by kvillios** [ant-media/Ant-Media-Server#2029]
# Issue
When I viewed videos from a local antmedia community server, I opened 6 browser windows and the video play normally. When I opened the 7th window the video on this window is not loading. When I close one browser window from the windows that the video is playing normally, then on the window that previous is not loading, now starts playing the video normally. 
The server ram and cpu aren't overloading at all.
The server has nginx as proxy and load balancer. 
Playing VoD Streams using WebRTCApp. The embedded code is:

<iframe width="560" height="315" src="//xxxxxxxx/WebRTCApp/streams/xxx/xxxx.mp4" frameborder="0" allowfullscreen></iframe>

### Environment
* RAM: 64 GB DDR4
* CPU: Intel® Core™ i7-6700 Quad-Core Skylake incl. Hyper-Threading Technology 
* Operating system and version: Ubuntu 18.04.4 LTS
* Java version: openjdk version "11.0.6" 2020-01-14
* Ant Media Server version: Ant Media Server Community 1.9.1
* Nginx version:  nginx/1.16.1
* /usr/local/antmedia/conf/red5.properties:
```
# HTTP
http.host=0.0.0.0
http.port=5080
https.port=5443
http.URIEncoding=UTF-8
http.max_keep_alive_requests=-1
http.max_threads=200
http.acceptor_thread_count=100
http.processor_cache=20
```
* Nginx settings from https://github.com/ant-media/Ant-Media-Server/wiki/Nginx-Load-Balancer

### Expected behavior
To have concurrent a lot of video viewers.

### Actual behavior
Only 6 concurrent video viewers are loading now.

Can you please advise?
Thank you in advance.
Konstantinos

**Comment by kvillios** [comment]
Any ideas please?

**Comment by kvillios** [comment]
Is a setting to change the concurrent video viewers on ant media server?

**Comment by mekya** [comment]
Sorry for not replying an earlier response. We've missed that. We'll schedule this issue to respond in this week.

**Comment by eneskuluk** [comment]
Could you provide the exact reproduce scenario please?
Did you open 7 different browsers or just tabs?
Also can you send your domain details and login credentials to my email please, enes.kuluk@antmedia.io? So i can test it out on your environment.

**Comment by mekya** [comment]
Let me add some things. 

I think one critical point is using the nginx as proxy and load balancer. I think it's worth to remove the nginx and testing the server directly.

**Comment by eneskuluk** [comment]
I have tested this without using nginx and outcome was good. I was using 2.2.1 community edition and java 11 on ubuntu 20.04
What i did is:
* Started Webrtc publishing.
* Open many tabs(around 10) on chrome and firefox.
* Plays well all on the tabs.
* Viewer count was only 3 because they were sharing same sessionid in the same browser. I tried 3 browsers simultaneously and seperately. Both was okey.

What i see on your end is you are using 1.9.1 with java 11.0.6. But Java 11 and version 1.9.1 are not compatible. You should use java 8 for version 1.9.1 and top of that you have nginx above these differences.
