### ISSUE TITLE
Webhook only firing on vodReady action

### ISSUE THREAD

**Issue by timmmmyboy** [ant-media/Ant-Media-Server#2036]
After adding a webhook in the app properties we only get a response to it when the vodReady action takes place. I am not seeing any activity to the webhook for liveStreamStarted or liveStreamEnded.

**To Reproduce**
1. Edited the red5-web.properties file following the guide at https://antmedia.io/webhook-integration/
2. Restart antmedia service
3. Monitor webhook call at https://webhook.site/

**Expected behavior**
According to the documentation a hook should fire when a live stream is started or ended as well as a VOD being created. Only the later is happening but nothing when a stream starts or ends.

**Comment by heldner** [comment]
Can confirm it, the issue is reproduced in snapshot 2.0 version. In 1.9.1 version webhook works fine.

**Comment by timmmmyboy** [comment]
I should have added my version, I'm on Enterprise Edition 1.9.1 20200112_1830 and seeing this.

**Comment by SelimEmre** [comment]
Hi all,

I tried Enterprise Editions 1.9.1 & 2.0.0 Snapshot versions. It works well in both versions. Maybe another problem may be causing it. Could you please send an e-mail to contact@antmedia.io so that we can investigate in more detail?

In 1.9.1 Enterprise Edition
![Screenshot from 2020-05-01 10-04-21](https://user-images.githubusercontent.com/9084130/80788945-41e1ec80-8b93-11ea-96ff-0975d738ed1f.png)

In 2.0.0 Snapshot Enterprise Edition
![Screenshot from 2020-05-01 10-04-18](https://user-images.githubusercontent.com/9084130/80788926-2b3b9580-8b93-11ea-8b43-da9d5976a996.png)

**Comment by rvjtech** [comment]
Seeing the same issue in Enterprise Edition 2.3.2 20210422_0456  Server is sending only when vodReady
![image](https://user-images.githubusercontent.com/45656750/120202574-5d12a600-c244-11eb-9648-1191c8438c24.png)

**Comment by rvjtech** [comment]
We are seeing webhook being called only vodReady event in Enterprise Edition 2.3.2 20210422_0456
![image](https://user-images.githubusercontent.com/45656750/120203081-f346cc00-c244-11eb-95be-5eda004db924.png)

**Comment by mekya** [comment]
Hi @rvjtech ,

Nevertheless, there are CI tests for web hooks on our end, there may be some problems. If you want, we can schedule a meeting together and take a look at your issue. 
 
Btw,  I've just tested with the latest version and it's working for me.

Regards,
A. Oguz
