### ISSUE TITLE
broken documentation

### ISSUE THREAD

**Issue by FedorovP777** [ant-media/Ant-Media-Server#21]
This written Ant-Media-Server-master/doc/rest/index.html 

> GET /broadcast/get 
> Get broadcast object

But not api resource http://localhost:5080/broadcast/get, return 404 error, not all '/broadcast' path.
And not it is written how authenticate in rest api.

**Comment by mekya** [comment]
Hi,

Ant Media Server has webapps so that rest services can be accessed through webapps. 
I mean you need to request to somewhere like this http://localhost:5080/LiveApp/broadcast/get 

Just check which apps are installed on your media server and call rest service with adding app name. 

Btw, If you are an enterprise client, you can directly send us e-mails about that. We generally respond enterprise e-mails less than 24 hours.

Regards,
A. Oguz
