### ISSUE TITLE
After publishing stopped, embed code plays random recording of stream

### ISSUE THREAD

**Issue by canat** [ant-media/Ant-Media-Server#2221]
A customer request:
Currently after publish stopped, the embedded webrtc player starts playing a recording of the stream (appears to be the first 10-40 seconds of the published stream), instead of just going blank or displaying the proper message.
This happens both for Chrome and Edge and is verified.
Customer wants that video goes blank or shows a message after publish stopped is received

**Comment by Glfarley** [comment]
If this thread is closed does that mean the bug is fixed?

**Comment by mekya** [comment]
I think there is some kind of ambiguity for this issue. 

This issue is about configuration for the embedded player. If stream has finished, embedded player checks  if stream goes live again. If it's live, then it play again. The reported problem happens when WebRTC play finishes then player take a look at if any HLS stream is available. So last seconds of the HLS streams is available in this case and it plays the last seconds.

In order to not have this issue. Just embed player with `playOrder=webrtc` query. Check the below documentation for more details. 

https://github.com/ant-media/Ant-Media-Server/wiki/Embedded-Web-Player

**Comment by Glfarley** [comment]
Thanks for the reply. You say I should set playOrder to just webrtc The
documentation you linked to says
Default value is webrtc,hls. *possible values are **hls,webrtc,webrtc,hls*

So is webrtc by itself also a valid argument for this parameter?

Glen Farley

**Comment by mekya** [comment]
>So is webrtc by itself also a valid argument for this parameter?

Yes it's true. If you just set playOrder to webrtc, it only tries to play with WebRTC.

**Comment by Glfarley** [comment]
Ok, thanks, we will change the embed code.

Glen Farley
