### ISSUE TITLE
Hash-Based token doesn't work properly in HLS Stream with Adaptive Streaming.

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2259]
**Describe the bug**
The hash-Based token feature doesn't work in HLS stream. Stream chunk files gives `Invalid Hash` error. WebRTC Stream working with a same token ID.

**To Reproduce**
1. Add 2 Adaptive Stream
2. Change hash-based parameters which are as below:
```
settings.hashControlPublishEnabled=true
settings.hashControlPlayEnabled=true
tokenHashSecret=testToken
```
3. Restart AMS
4. Publish RTMP streaming with a token ID. 
5. HLS stream chunk files give 403 permission denied due to `Invalid Hash`

**Expected behavior**
It should work properly :)

**Screenshots**
![Screenshot from 2020-06-16 15-07-35](https://user-images.githubusercontent.com/9084130/84772963-5e6fa200-afe4-11ea-9f54-c69188dd4234.png)

![Screenshot from 2020-06-16 15-07-24](https://user-images.githubusercontent.com/9084130/84772983-692a3700-afe4-11ea-9923-5b8dc86e5a72.png)

**Additional context**
Tested in Ant Media Server latest 2.1 SNAPSHOT.

**Comment by benbowler** [comment]
Was this fixed in a later version or abandoned? I'm seeing the same as of 28 April 2021.

**Comment by mekya** [comment]
Let me re-open the issue and confirm the case again.

**Comment by benbowler** [comment]
I can add some further information, it seems that when using tokens on adaptive bitrate streams:

1. The token is not required or passed to the single bitrate versions within a multi-bitrate stream - I feel like for security, each bitrate should also require a token (otherwise a viewer could guess the single bitrate URL and watch without a token)

Current file at: liveLocal/streams/live-608be7e104784e1fc45b8ee5-event-4978dae7d1c461fe1f35f34e58135f99c959_adaptive.m3u8?token=c0c447ab0c9d59d923197cd9e7dj3e50dcd78a0e013cf8b5260adab0d918b008"

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=272112,RESOLUTION=416x234,CODECS="avc1.42e00a,mp4a.40.2"
live-608be7e104784e1fc45b8ee5-event-4978dae7d1c461fe1f35f34e58135f99c959_240p.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=875040,RESOLUTION=832x468,CODECS="avc1.42e00a,mp4a.40.2"
live-608be7e104784e1fc45b8ee5-event-4978dae7d1c461fe1f35f34e58135f99c959_480p.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1791216,RESOLUTION=1280x720,CODECS="avc1.42e00a,mp4a.40.2"
...
```

Should be this IMHO:

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=272112,RESOLUTION=416x234,CODECS="avc1.42e00a,mp4a.40.2"
live-608be7e104784e1fc45b8ee5-event-4978dae7d1c461fe1f35f34e58135f99c959_240p.m3u8?token=c0c447ab0c9d59d923197cd9e7dj3e50dcd78a0e013cf8b5260adab0d918b008
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=875040,RESOLUTION=832x468,CODECS="avc1.42e00a,mp4a.40.2"
live-608be7e104784e1fc45b8ee5-event-4978dae7d1c461fe1f35f34e58135f99c959_480p.m3u8?token=c0c447ab0c9d59d923197cd9e7dj3e50dcd78a0e013cf8b5260adab0d918b008
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1791216,RESOLUTION=1280x720,CODECS="avc1.42e00a,mp4a.40.2"
...
```

2. Each single bitrate member of the adaptive bitrate stream is not being served with the correct CORs headers. For development, I have opened up the CORs header to allow from "*" and the _adaptive.m3u8 file loads fine, however, the single bitrate m3u8 files are missing with `Access-Control-Allow-Origin` error.

```
Access to XMLHttpRequest at 'https://example.com:5443/liveLocal/streams/live-608be7e104784e1fc45b8ee5-event-4978dae7d1c461fe1f35f34e58135f99c959_720p.m3u8' from origin 'http://localhost:8085' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

<img width="1375" alt="Screenshot 2021-05-05 at 12 51 52" src="https://user-images.githubusercontent.com/119352/117137900-4b9fc080-ada2-11eb-9c1c-dbe82e81b696.png">

**If I set `settings.hashControlPlayEnabled=false` and restart the Ant Media Server the CORs error goes away.**

I can provide a demo of this privately via the Slack channel if needed.

**Comment by SelimEmre** [comment]
Hi @benbowler,

Thank you for your great questions. Let me explain:

1- AMS is allowing to get requests according to Session ID in One Time token system. So if any user can access a play with adaptive file, they can also access single bitrate files which are same stream ID with same session ID.
Btw, I already added a pull request for your issue. You can check it: https://github.com/ant-media/StreamApp/pull/151/files#diff-df443c20afd341b366bd2b2691ffdc189bce111feb301a1e3ced0eccacaec3eaR283
With above development, videojs player adding parameters to all requests

2- `For development, I have opened up the CORs header to allow from "*" and the _adaptive.m3u8 file loads fine`
Could you please give me more detail about this part? How can you enable in your environment? 

`I can provide a demo of this privately via the Slack channel if needed.`
It would great to understand this issue. I sent message on Slack.
