### ISSUE TITLE
S3 integration VOD still trying to play local file

### ISSUE THREAD

**Issue by Fyb3roptik** [ant-media/Ant-Media-Server#2314]
### Short description
After enabling S3, the VOD section errors because its not pulling the vod from S3

### Environment

* Operating system and version: Ubuntu 18.04
* Java version: 
* Ant Media Server version: Community Edition 2.0.0 20200504_1842
* Browser name and version: Chrome latest

### Steps to reproduce
1. Enable S3
2. Live stream
3. Go to VOD section and try to play media, it tries to play it locally instead of via the s3 url

### Expected behavior
The url should be to the S3 video instead of the local one

### Actual behavior
It currently points to the local video path

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Thank you for your question @Fyb3roptik 

There is forwarder for that. You can add following properties to your application properties file (WEB-INF/red5-web.properties)

```
settings.httpforwarding.extension=mp4
settings.httpforwarding.baseURL={YOUR_S3_URL}
```

**Comment by Fyb3roptik** [comment]
I have done this already. It is not working as expected

**Comment by Fyb3roptik** [comment]
<img width="1295" alt="Screen Shot 2020-07-21 at 12 14 57 PM" src="https://user-images.githubusercontent.com/339131/88085818-fd3f6f00-cb4b-11ea-9603-0167691ae63d.png">
<img width="1614" alt="Screen Shot 2020-07-21 at 12 13 46 PM" src="https://user-images.githubusercontent.com/339131/88085822-fe709c00-cb4b-11ea-9056-f65c66bba2e3.png">

**Comment by Fyb3roptik** [comment]
@mekya Anything? Is there a way I can do a PR for this?

**Comment by mekya** [comment]
Hey @Fyb3roptik,
 
Sorry I've missed your previous comment. 

> Notice the video url is pointing to local instead of S3
Server redirects the incoming request on the HTTP level with a filter. I mean you cannot see the redirect url there.  

I think you can see the redirect url through developer console. Could you please check that if the url is correct and points out the correct location?

**Comment by Fyb3roptik** [comment]
It does not. Looks like it is still pointing to local

**Comment by mekya** [comment]
Then I need to test on my side and confirm it.

**Comment by mekya** [comment]
Hey @Fyb3roptik ,

I've tested on my end with the 2.0 Community version. Let me tell what I have done. 

* I've opened the `webapps/LiveApp/WEB-INF/red5-web.properties`. I've added following properties there
```
settings.httpforwarding.extension=mp4
settings.httpforwarding.baseURL=http://url/for/forwarding/
```

* I've started the server. Because we make manual conf change, we need to restart the server. 
* I've enabled MP4 recording on the web panel. 
* I've send a stream to the stream and it's recorded as stream1234.mp4
* After that I've tried to play on web panel. 

I expect to see that stream1234 is being forwarded to `http://url/for/forwarding/` in the developer tools of chrome.
It's working for me. Take a look at the screenshot below. Maybe you're missing the `streams` directory in the target. 

<img width="1490" alt="Screen Shot 2020-08-09 at 11 13 14" src="https://user-images.githubusercontent.com/3456251/89727997-2f990980-da32-11ea-9b83-39572b28f40e.png">

**Comment by Fyb3roptik** [comment]
Ok weird, it is working now. I restarted and everything and I guess maybe it was cached somehow. Thanks for the help!

**Comment by mekya** [comment]
My pleasure

**Comment by bharat-ux** [comment]
> 
> 
> Thank you for your question @Fyb3roptik
> 
> There is forwarder for that. You can add following properties to your application properties file (WEB-INF/red5-web.properties)
> 
> ```
> settings.httpforwarding.extension=mp4
> settings.httpforwarding.baseURL={YOUR_S3_URL}
> ```

how can you explain deeply

**Comment by bharat-ux** [comment]
it's now working
