### ISSUE TITLE
LHLS

### ISSUE THREAD

**Issue by ithirzty** [ant-media/Ant-Media-Server#2369]
Will there ever be LHLS (Low latency HLS) support? Would it be supported in the community edition?

Thanks.

**Comment by mekya** [comment]
Hey @ithirzty ,

Yeah it's already scheduled for v2.2.  There is an on-going development about that.  

Let me also give an update about the current development. 

FFmpeg has not implemented Apple's LHLS yet. So that we plan to provide Low Latency Dash at first. 
After FFmpeg implements Apple's LHLS we will also integrate it.

Lastly, it's not decided yet whether to provide LHLS and LDASH in community or enterprise.
