### ISSUE TITLE
Add support for a SSL certificate authority that doesn't suck

### ISSUE THREAD

**Issue by chris00001** [ant-media/Ant-Media-Server#2388]
I'm frustrated by the rate limits set by Lets Encrypt in your "super simple" one click solution and the unbearably short life of Lets Encrypt certificates. I should NOT have to re-up it ever 3 months. It's ridicules. 

Solution: 

Add documentation for using some other SSL certificate authority.

**Comment by mekya** [comment]
Hi @chris00001 ,

I see.  There are some simple tricks may help you for that. 

* You can import other SSL certificates with `enable_ssl.sh` as follows.

```
./enable_ssl.sh -f {FULL_CHAIN_FILE} -p {PRIVATE_KEY_FILE} -d {DOMAIN_NAME}
```

* You don't need to get a new certificate from the Let's Encrypt for every time. You can use the same one if you're in the same instance.  So that you don't get stuck in the weekly limits.

* There is an auto renewal SSL cron job for running every 3 months. It's installed by default when you first install the SSL in the latest version.

**Comment by reiluke** [comment]
how to generate fullchainfile from cloudflare, i have pem and key

**Comment by muratugureminoglu** [comment]
The proxy must be active (http/https) to use Cloudflare certificates and if the proxy is active, unfortunately, Ant Media Server will not work because it uses different ports and protocols. My advice to you is to use Let's Encrypt.

https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/
