### ISSUE TITLE
start broadcast when the client only connected ?

### ISSUE THREAD

**Issue by moragab1993** [ant-media/Ant-Media-Server#2441]
Hello

i was wondering if there's a way to start the broadcast of stream source only when the client is connected and stop it when the client disconnect ?

thanks

**Comment by eneskuluk** [comment]
If you want to publish from both sides, you need to make a connection in the application's network layer.

If you want to watch a stream source that is not currently not publishing and want to start streaming whenever you connect, you can try implementing the following code:
```
function tryToPlay(name, token, noStreamCallback) {
	fetch("rest/v2/broadcasts/"+name,{method:'HEAD'})
	.then(function(response) {
		if (response.status == 200) {
			initializeWebRTCPlayer(name,token,noStreamCallback);
		}
		else 
		{
					fetch("rest/v2/broadcasts/"+name+"/start",{method:'POST'})
					.then(function(response){
						if(response.status==200)
						initializeWebRTCPlayer(response.streamId,token,noStreamCallback);

					}).catch(function(err){
						console.log("Error: "+ err);
					})
					console.log("No stream found");
					if (typeof noStreamCallback != "undefined") {
							noStreamCallback();
						}
		}
	}).catch(function(err) {
		console.log("Error: " + err);
	});
}

```
The code above will try to start a stream on provided stream id which is your stream source. You can call this function in play.html where you use trytoplayHLSPlay or in your custom application.

And when you have no viewer you can call to stop publish `fetch("rest/v2/broadcasts/"+name+"/stop",{method:'POST'})` and follow the format above where you check response.status and etc.

But be cautious about the code above because it is not a production level code and may lead security issues if you use it directly. You need to implement this in the application level. The code above is to give you insight about how this could be achieved and should not be used directly.
