### ISSUE TITLE
Microphone and Laptop Audio with Screen Share

### ISSUE THREAD

**Issue by rahulkent** [ant-media/Ant-Media-Server#2466]
**Is your feature request related to a problem? Please describe.**
1.	User 1 shares Screen with Video on.
2.	User 2 is able to view User 1 as well its Screen and also listen to Audio (Microphone of User 1).
3.	Now suppose while sharing the Screen User 1 tries to play a Video.
4.	After this User 2 can view the Video being played on User 1’s screen but cannot listen to the Audio of that particular Video.
This happens even if below ‘Share Audio’ flag was selected while sharing the screen.

**Describe the solution you'd like**
End User should listed to Audio from Video as well as from Microphone

**Describe alternatives you've considered**
https://paul.kinlan.me/screen-recorderrecording-microphone-and-the-desktop-audio-at-the-same-time/

**Additional context**
None

**Comment by golgetahir** [comment]
Hi,

This has been developed while we are changing the ecma5 to ecma6 actually. Looking at the date of the issue it is not been yet released so this issue is no longer exist.
The commit is: https://github.com/ant-media/StreamApp/commit/a9ac08d1c2d50a417e2572b051fb57a71395c8e5

If you have further problems still with the latest versions of Ant Media about this please reach back to me.

Cheers
