### ISSUE TITLE
Android Live broadcaster streams not receiving 

### ISSUE THREAD

**Issue by TheTechTitan** [ant-media/Ant-Media-Server#2484]
I am using self hosted ant media server on my PC virtual machine. what should be the base url I should give , i tried both  rtmp://<server-ip>/LiveApp/   and  rtmp://<server-ip> : <port>/LiveApp/    but still not receiving the streams on localhost:5080 management console.

**Comment by golgetahir** [comment]
Hi,

For the base url, you need to write the IP address of your media server running, such as `rtmp://SERVER_IP_ADDRESS/LiveApp/` . In your case, the IP address should be the address of virtual machine where the server is running.

Thanks

**Comment by TheTechTitan** [comment]
Hi,

my virtual machine IP address is 10.0.2.15 so i tried both 

rtmp://10.0.2.15:5080/LiveApp/
rtmp://10.0.2.15/LiveApp/

Unfortunately, I still do not see the incoming streams on my console. server is up and running. Is it something to do with  network, In virtual machine my attached network is NAT

![image](https://user-images.githubusercontent.com/48148088/94294543-9c824780-ff7d-11ea-83de-48b866a2bc97.png)

**Comment by golgetahir** [comment]
Hi @TheTechTitan , I meant that the virtual machine ports should be reachable from the internet, which most of the NAT's does not allow. If your NAT allows then you need to write the public IP address. Otherwise, you need to connect to the same network, it should work behind the same network. So in this case your devices IP should probably start with also something like 10.0 ( which seems like a local IP rather than public IP ). There are 4 types of NAT and they don't allow you to connect to the ports because of the security reason.
