### ISSUE TITLE
Safari in IOS missing audio when disconnection and reconnection happens.

### ISSUE THREAD

**Issue by eneskuluk** [ant-media/Ant-Media-Server#2490]
### Short description
 When a Safari on iOS device disconnects and then reconnects (through a new adaptor object) all subsequent streams are published without audio.

### Environment

* Ant Media Server version:2.1
* Browser name and version:Safari in IOS

### Steps to reproduce
1. Load the page in Safari on iOS
2. Click connect (wait for log to appear below buttons)
3. Click publish (wait for log to appear below buttons)
4. Click stop publish (wait for log to appear below buttons)
5. Click disconnect

Wait for your camera to turn off and then do it all again

6. Load the page in Safari on iOS
7. Click connect (wait for log to appear below buttons)
8. Click publish (wait for log to appear below buttons)
9. Click stop publish (wait for log to appear below buttons)
10. Click disconnect

### Expected behavior
Both streams should have recorded with the audio.

### Actual behavior
Second stream does not have audio recorded.

 
### Extra information
V1.9 does not have this issue but v2.1 has this.

**Comment by mekya** [comment]
Hi,

I've just tried to re-produce the problem on my end. However I couldn't reproduced that. I've used the WebRTCAppEE/index.html for that.  I mean both videos have the sound. The only thing in the scenario above is the item in 'Click Disconnect'. I don't see any disconnect button. Exactly which html file are you mentioning?

Regards,

**Comment by cdanzig** [comment]
Here is the original bug report. I think some information may have been
lost when it was translated into a ticket in github:

We have a bug to report for the webrtc_adaptor.js version that comes with
v2.1. When an iOS device disconnects and then reconnects (through a new
adaptor object) all subsequent streams are published without audio.  We
have created a very simple page that can reproduce the issue here:
https://cameratag.com/test.html. We have confirmed that the same code using
the earlier (1.9) version of the webrtc_adaptor.js does not have the same
issue. Our best guess is that the rtcAdaptor is perhaps not destroying an
AudioContext when the stream is disconnected but this is without really
digging in.

1. Load the page in iOS
2. Click connect (wait for log to appear below buttons)
3. Click publish (wait for log to appear below buttons)
4. Click stop publish (wait for log to appear below buttons)
5. Click disconnect

Wait for your camera to turn off and then do it all again

6. Load the page in iOS
7. Click connect (wait for log to appear below buttons)
8. Click publish (wait for log to appear below buttons)
9. Click stop publish (wait for log to appear below buttons)
10. Click disconnect

Note that your first stream recorded with audio and that the second did
not. We have been forced to switch back to using the old version of the JS
library which obviously does not support any of the new presence polling
functionality so we are without the ability to launch our "rooms" feature.
After you've had a chance to look at this I'd love to get your thoughts on
any potential work-arounds and/or a timeline for a potential fix.

Best,
Chris

P.S. it looks like you're releasing the new version webrtc_adaptor.js in
ECMA6- we still have to support older browsers that don't support ECMA6 so
it would be nice to also have a transpiled version available for ECMA5
(right now we're just using babel to do it ourselves)

**Comment by mekya** [comment]
Hi Chris, 
Thank you. I'm trying to re-produce the problem and will update you about that. 

Thank you for the ECMA5 report. We have plan to fully switch to ECMA6 in WebRTC Adaptor and I think we can yeah provide a transpiled version for ECMA5.

**Comment by mekya** [comment]
Hi Chris,

Yeah I've reproduced the case on my end. Trying to figure out the problem. 

FYI

**Comment by cdanzig** [comment]
Great!

**Comment by mekya** [comment]
Hi @cdanzig ,

I've working on this since yesterday. I confirm that yeah it's a problem. I find out the problem. iOS does not capture the mic audio in the second attempt. I've checked that in v1.9.1. The same problem also exists there. 
I think it may not about the Ant Media Server version. It may about the iOS version. I find this -> https://support.frozenmountain.com/hc/en-us/articles/360036546954-Known-Issue-with-iOS-Safari-13 

Anyway, I'm still trying to figure out some kind of workaround for that. I just want to let you know that. 

FYI

**Comment by mekya** [comment]
Hi @cdanzig ,

Shame on me :) There is no problem with iOS version or something. I've just fixed the issue. Just add 
`audioTrack[0].stop();` method on this line
https://github.com/ant-media/StreamApp/pull/73/files#diff-2b9ebb7eac397ec90e39b8e850d39353R228

I've tested and it's working for me now. You can try it on your end.

**Comment by cdanzig** [comment]
We will give it a test this weekend. Thanks so much for digging into this
for us! Why is it that the hardest problems always have the simplest
solutions? :)

-c

**Comment by mekya** [comment]
I think there is absolutely very close relation between software development and philosophy :P
