### ISSUE TITLE
Getting publishTimeoutError after network interruption publishing in Windows 10

### ISSUE THREAD

**Issue by Qolzam** [ant-media/Ant-Media-Server#2519]
### Short description
After network interruption,I handle reconnecting the AntMedia by invoking `publish()` method. In **Mac** the stream back to stable state but in **Windows** I get publish timeout Error

### Environment

* Operating system and version: Windows 10
* Java version: 
* Ant Media Server version: Enterprise 2.1
* Browser name and version: Chromium 80.0.3987.86 (Electron 8.0.0)

### Steps to reproduce
1. Disconnect network and connect after some 20 seconds.
2. Connect network again.
3. Invoke `publish()`  method.

### Expected behavior
After network interruption and invoking `publish()` method, the stream should recover. 

### Actual behavior
After network interruption and invoking `publish()` method, I receive `publishTimeoutError`. 
 

### Logs
- Websocket connection log
![image](https://user-images.githubusercontent.com/8446573/93752479-eccd7280-fc28-11ea-99cb-37fd3ace56fd.png)

**Comment by mekya** [comment]
Thank you for the report. We'll try to schedule this issue asap.

**Comment by Qolzam** [comment]
Hello @mekya. Thank you for your reply.
I did work around and solve it with creating new offer. I send a SDP offer and after 3 seconds invoke `publish()` method. With this I can see ICE communication complete successfully! But I haven't found the cause of `publishTimeoutError`.

**Comment by mekya** [comment]
Thank you for your workaround @Qolzam . I think it will give some ideas to @golgetahir who is responsible for this issue.

**Comment by golgetahir** [comment]
Hi @Qolzam 

I investigated your problem. One of the reasons for `publishTimeoutError` is that trying to send publish command to the server without any connection. From your work around solution, one idea come to my mind is that you are trying publish before connection is established in windows since it is solved after you wait a little. 

In our sample page, we implemented the network interruption similar to your work around solution as I give the code below and it has no problems working in windows. I think it is not bad practice to reconnect the server with a clean instance. If you don't want to implement like this, to help you I need to check your application codes and server logs if you can send it to tahir.golge@antmedia.io

You can find all of the implementation in https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/index.html if you want to.

```
checkAndRepublishIfRequired() {
	 	var iceState = webRTCAdaptor.signallingState(streamId);
		console.log("Ice state checked = " + iceState);
	  	if (iceState == null || iceState == "failed" || iceState == "disconnected"){
	  		console.log("Publish has stopped and will try to re-publish");
	  		webRTCAdaptor.stop(streamId);
	  		webRTCAdaptor.closePeerConnection(streamId);
	  		webRTCAdaptor.closeWebSocket();
	  		initWebRTCAdaptor(true, autoRepublishEnabled);
	  	}
}
```

**Comment by Qolzam** [comment]
Hi @golgetahir ,

Thank you for information and the solution! 
It seems you have a cleaner solution than my workaround. But let me try the solution on my side and back to you with the result asap.
By the way I am wonder why Mac OS can keep the connection but Windows not! 

> NOTE: For Windows I open the WebSocket (for AntMedia) after network interruption but for Mac I don't need to that.
