### ISSUE TITLE
Command to update version

### ISSUE THREAD

**Issue by ismaelazanza** [ant-media/Ant-Media-Server#2659]
Say the question but I'm new to Ant-Media-Server, I want to update from an old version to the current one but I can't get the command to do it through the ssh terminal, I'm using ubuntu 18. I appreciate the help.

**Comment by golgetahir** [comment]
Hi,

You need to download new version, then download the latest install script;

`wget https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh && chmod 755 install_ant-media-server.sh`

Then run the installation script adding true to the end so that it will keep your previous settings and update, this is how you update Ant Media Server.

`sudo ./install_ant-media-server.sh [ANT_MEDIA_SERVER_INSTALLATION_FILE] true`

**Comment by mekya** [comment]
Closing this issue. Please feel free to open if you have some problems with that.
