### ISSUE TITLE
Adaptive bitrate decreases to lowest resolution

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#2829]
# Issue

### Short description
Video quality decreases the lowest resolution and it shows weak network connection. 
On the other hand, when it's forced to higher quality, it plays smoothly. Secondly, bandwidth is measured high in speedtest.net

### Environment

* Operating system and version: Ubuntu 18.04
* Java version: 11
* Ant Media Server version: 2.2.1
* Browser name and version: Chrome

### Steps to reproduce
1. Add three adaptive bitrates 720p, 480p, 240p
2. Enable VP8 and Disable H264
3. Send stream to Ant Media Server with rtmps 1080p, 2.5Mbps

### Expected behavior
Automatic quality playback should stream with 720p

### Actual behavior
Quality decreases to 240p
 

### Logs

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by golgetahir** [comment]
Hi,

I tried this issue on our test server with rtmp and OBS the result was giving me the expected behavior as it starts with 720p if we don't force any quality;

![Screenshot from 2020-12-30 13-16-39.png](https://images.zenhubusercontent.com/5f5216048e8ed816963da716/a9653c4f-1c99-4a85-a853-f3d4ce4552e8)

OBS configurations are;

![Screenshot from 2020-12-30 13-19-04.png](https://images.zenhubusercontent.com/5f5216048e8ed816963da716/0a117d1c-7b85-4480-a566-f58a9965d076)

Ant Media settings;

![Screenshot from 2020-12-30 13-21-11.png](https://images.zenhubusercontent.com/5f5216048e8ed816963da716/09d85a92-a098-4532-8427-901461d8f101)

We will investigate this further with rtmps also.

Thanks

**Comment by rjmtldo** [comment]
@golgetahir  may i know how long did it stay to 720p resolution? cause in our testing using adaptive bitrate it will start to 720p, after few minutes it will change to low quality.

**Comment by golgetahir** [comment]
Hi @rjmtldo

I wish you a happy new year,

The broadcast is on for 15 mins now, are you using the server on your machine or a cloud? Are you using a dedicated machine? My speed test results are also like this,

![Screenshot from 2021-01-04 12-48-51.png](https://images.zenhubusercontent.com/5f5216048e8ed816963da716/afe31ebd-be0d-4fce-badf-c85dce1ef6cc)

![Screenshot from 2021-01-04 12-49-01.png](https://images.zenhubusercontent.com/5f5216048e8ed816963da716/ef0fe9dc-b5c4-4bd3-8078-5cfdb8ab8420)

![Screenshot from 2021-01-04 12-53-21.png](https://images.zenhubusercontent.com/5f5216048e8ed816963da716/52587c39-7a0c-4561-bd15-5c6cd56e4e9c)

**Comment by rjmtldo** [comment]
@golgetahir  yes our server is hosted in cloud 
![image](https://user-images.githubusercontent.com/72129826/103523209-219ac800-4eae-11eb-9f8f-c9f6e8b8d43f.png)

and for my workstation test machine 
![image](https://user-images.githubusercontent.com/72129826/103523378-53ac2a00-4eae-11eb-92e2-d22c376a1f55.png)

what would be the issue here? is it our internet connection? i don't think  that it is an issue with our bandwidth. and there's some complaints we received from our viewers they also got the same results.

**Comment by rjmtldo** [comment]
@golgetahir 
 i'm free today to help you troubleshoot the problem.

**Comment by golgetahir** [comment]
@rjmtldo Speed test sometimes differs from the connection speed between client and server. Can you reach me from tahir.golge@antmedia.io and explain your use case also your server address and ssh information ( I am asking for an e-mail for not sharing this in public ) for me to check if there is anything going wrong on the server software and to observe the issue scenario.

**Comment by rjmtldo** [comment]
ok ill email you shortly

**Comment by rjmtldo** [comment]
@golgetahir 
 i just sent you an email.

**Comment by rjmtldo** [comment]
hello @golgetahir just to ask , do we have update on this one?

**Comment by golgetahir** [comment]
Hi @rjmtldo

I sent you an e-mail this morning about the issue, as I watched your screen record I see that your network's packet loss goes up to 195 whereas as you can see mine is 1-2. Even though your network speed is fine if your packet loss is in those levels it will go on like that and it is a network issue. The issue here is depending on that, also your jitter is pretty high. There are no issue on server's quality adjustment mechanism in fact it is working quite fine since there is packet loss like that and also from the tests. 

Thank you

**Comment by rjmtldo** [comment]
Hi Tahir,  i will check with our  provider, but it's impossible also to check every of our viewers isp right? i'm not only the one who experiencing this not only our network but also all of our viewers network.  besides can you give me the test result of your screenshots/video recorded of  your jitter,  speedtest   and latency and how long you been running the stream?

**Comment by golgetahir** [comment]
Rj, I already gave you those informations above, I will send a video to your mail also, here it is this broadcast is on for more than 5 minutes;

![Screenshot from 2021-01-07 12-11-11.png](https://images.zenhubusercontent.com/5f5216048e8ed816963da716/78b374ef-8053-4488-9fbd-0a9298dd7c0c)

It is impossible to check your viewers isp, you need to check your server's connection ( your cloud provider or which platform it is running on ) You can use our webrtc-test-tool instead of speed test, speed test is not a tool to measure your server's capability for streaming.

https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/webrtc-test-tool.html

**Comment by rjmtldo** [comment]
can you do a test using my server ?  i will give you access give me your test results.

**Comment by rjmtldo** [comment]
@golgetahir hi i just sent you an email. regarding to our cloud provider.

**Comment by rjmtldo** [comment]
@golgetahir  we will try to install antmedia in aws. we will let you know the results
