### ISSUE TITLE
Custom SSL certificates doesn't work properly in enable_ssl script

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#2840]
### Short description
I created SSL certificates via openssl. I just followed below commands:

`openssl req -newkey rsa:4096 -x509 -sha256 -days 3650 -nodes -out ams.crt -keyout ams.key`
But it's not worked with below command in my environment:
`sudo ./enable_ssl.sh -f ams.crt -p ams.key -d domain.com`

After that, I used v2.1 enable_ssl script. It worked.

### Environment

* Operating system and version: Ubuntu 18.04
* Java version: 11
* Ant Media Server version: 2.3.0 SNAPSHOT

### Steps to reproduce
1. Just create SSL certificates and try with enable_ssl script.

### Expected behavior
I expected it should work.

### Actual behavior
It's not working properly.

### Logs
```
mypc@mypc:/usr/local/antmedia$ sudo ./enable_ssl.sh -f ams.crt -p ams.key -d domain.com
domain: domain.com

Importing keystore /usr/local/antmedia/domain.com/fullchain_and_key.p12 to /usr/local/antmedia/domain.com/keystore.jks...
Certificate stored in file </usr/local/antmedia/domain.com/tomcat.cer>
Certificate was added to keystore
cp: missing destination file operand after '/usr/local/antmedia/conf/chain.pem'
Try 'cp --help' for more information.
There is a problem in installing SSL to Ant Media Server.
 Please take a look at the logs above and try to fix.
 If you do not have any idea, contact@antmedia.io
```

**Comment by muratugureminoglu** [comment]
Hi @SelimEmre 

chain.pem file added in version 2.3. Since there is no chain file in the Self-Signed certificate, you can use it as follows.

`/usr/local/antmedia/enable_ssl.sh -f ams.crt -p ams.key -c ams.crt -d domain.com`

[https://github.com/ant-media/Ant-Media-Server/wiki/Frequently-Asked-Questions#how-to-use-self-signed-certificate-on-ant-media-server](https://github.com/ant-media/Ant-Media-Server/wiki/Frequently-Asked-Questions#how-to-use-self-signed-certificate-on-ant-media-server)
