### ISSUE TITLE
Data Channel Error when one of the participant is close

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#2848]

**Comment by eneskuluk** [comment]
According to user report, assume that there are 3 users in the conference. User A, B C. When user C connection drops or disconnects, Data channel between A and B gets broken and shows error on console.
But, WebRTC does not work in this manner. There is no relation between User A, B and C.
In WebRTC, There are publisher and player. When user C disconnects or drops, Data Channel error is shown on console because on player side, data channel is being broken with the publisher. So that is why this happened.
I developed a custom conference.html to test it and confirmed no datachannel error occurs between user A and B. This is the expected behaviour.
