### ISSUE TITLE
WebRTC - Latency increase up to 3 seconds

### ISSUE THREAD

**Issue by jesusmunozmobivery** [ant-media/Ant-Media-Server#2884]
### Short description
Latency in WebRTC streaming increase up to 3 seconds in all the tests that our client did.

Ticket ID: 37030

### Environment

* Operating system and version: Digital Ocean Droplet (Basic / 1 GB / 1 vCPU)
* Ant Media Server version: Enterprise Edition 2.1.0 20200720_1328

### Steps to reproduce
1. An user creates a streaming channel and starts broadcasting through a mobile device.
2. Several users connect to that channel in order to receive the signal from the user who is broadcasting.

Mobile devices are iOS or Android. This problem is recurring regardless of the device.

### Expected behavior
Ultra low latency streaming by using WebRTC technology with ~0.5 seconds latency

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Thank you for the issue. We'll assign someone to respond this issue soon.

**Comment by eneskuluk** [comment]
Thank you for posting this!
Could you confirm that latency increases as number of viewers increase right?
This is mostly because your droplet is `1GB, 1 core` machine which is not that capable.
By the time, when user count increases, your droplet is unable to deliver stream fast enough to viewers. 

So, probably that's why this happens.

**Comment by mekya** [comment]
Let me add some more things. 

There is generally a bandwidth issue in Digital Ocean in some other instance types as well. 

In the [following issue 2550](https://github.com/ant-media/Ant-Media-Server/issues/2550)  
We've a test with this instance 
```
CPU-Optimized
Dedicated CPU
16 vCPUs
```

We've figure out that bandwidth is about 300-350Mbps and bottleneck is the bandwidth in this instance type. 
Even if there is a CPU in the server, latency increases due to lack of bandwidth. 

Check this comment
https://github.com/ant-media/Ant-Media-Server/issues/2550#issuecomment-707529923

**Comment by jesusmunozmobivery** [comment]
Thanks for your response.

During a recent test on the Digital Ocean droplet, the CPU and RAM are apparently normal.
In the test, 10 viewers were connected to an audio-only stream.

CPU peaks at 70% usage and RAM remains constant at 60% usage.

I attach a screenshot of the bandwidth usage during that test.

![image](https://user-images.githubusercontent.com/77431293/105954268-bdb28c00-6074-11eb-8904-a6e4ea1d72de.png)

Thank you.

**Comment by mekya** [comment]
Hi @jesusmunozmobivery ,

I see. Do you have Round Trip Time(RTT) information in your tests? As far as I remember, we show round trip time in publishing and playing. If RTT is high, then it's normal that you see higher latency.

TBH, some of our users are migrating from Digital Ocean to AWS in order to resolve these kind of problems. AWS users are generally happy with that.

**Comment by jesusmunozmobivery** [comment]
Hi @mekya ,

No, I don't have RTT information. How can I see this metric?

If this issue continues, we will move to AWS and will do the same tests. But that will be the last alternative

**Comment by mekya** [comment]
Hi @jesusmunozmobivery ,

You can take a look at the chrome://webrtc-internals
Alternatively, we show these parameters in publisher and player pages. 

I think you can try CPU optimized instance in Digital Ocean
https://www.digitalocean.com/products/droplets/
