### ISSUE TITLE
Protecting Stream ID on CE

### ISSUE THREAD

**Issue by jfreak53** [ant-media/Ant-Media-Server#2888]
Is there any way at all to protect the stream ID in the CE edition? I read a short blip in one of these issues about a different stream ID for playing as opposed to viewing/embedding, but combing through the docs I cannot find it anywhere.

1. Is there a way to have two different stream ID's, one for embedding live video on a website, and two for streaming to it.
2. Or is there another way to protect streaming without using hash tokens?

CE edition is what I'm asking, I know there are hash tokens in EE. But I need to see if there is a way to protect streaming other than IP in the CE edition.

Docs are not giving me anything and I'm not finding anything here in the Issues thread.

Thanks in advance!!

**Comment by eneskuluk** [comment]
As you mentioned, these are the features that are supported in Enterprise edition such as One-time token, hash based token, time based tokens etc.
1: We don't have this feature in built-in even in Enterprise edition.
2: Sadly we don't have this in Community Edition. It is hard to protect streams without tokens or hashing. It is even harder to do that without hashing/tokens in HLS stream since it is HTTP based.

I wish I could provide a resolution here to you.

Best Regards,
Enes.
