### ISSUE TITLE
RTMP streams to early announced to a web hook as ready

### ISSUE THREAD

**Issue by kputyra** [ant-media/Ant-Media-Server#3034]
### Short description
I'm streaming camera using FFMPEG over RTMP and using a web hook to detect when the stream is live. Once AntMedia calls the web hook with action=liveStreamStarted, a web browser client sends 'play' command to AntMedia over a web socket, in order to initiate a WebRTC connection. The AntMedia replies with the error 'no_stream_exists'.

### Environment

* Operating system and version: Ubuntu 16.04 (server with camera), Windows 10 (web client)
* Ant Media Server version: Enterprise Edition 2.2.1
* Browser name and version: Chrome 88

### Steps to reproduce
1. Web browser: open a web socket connection to wss://ant-media-sever-instance:5443/WebRTCAppEE/websocket
2. Web browser: open a web socket connection to some signaling server (I'm using nchan on nginx)
3. Server: make REST API call to create a stream with id=<streamId> and listenerHookURL=<webhook.php>
4. Ubuntu: stream video camera with FFMPEG to rtmp://ant-media-server-instance/WebRTCAppEE/<streamId>
5. webhook.php forwards AntMedia notifications to the web client (in my case: using nchan)
6. When the web client receives a confirmation that the stream is broadcasting, send 'play' command to Ant Media over the web socket connection to initiate streaming.

### Expected behavior
Ant Media replies with 'takeConfiguration'.

### Actual behavior
Ant Media replies with 'no_stream_exists'. A Rest API request (GET /broadcasts/<streamId>) shows the stream status as broadcasting, though. Only after several seconds is the stream accessible.

### Notes
1. The issue does not appear for streams published over WebRTC. In this case once the web hook receives and forwards liveStreamStarted notification, the client can fetch the stream immediately.
2. Instead of using a web hook, I've tried polling Ant Media with REST API to check the status of the stream. Once I saw 'broadcasting' I sent the command 'play', but the answer was again 'no_stream_exists'.
3. I've tested it with recording turned off and adaptive bitrate either on or off (does not affect the outcome).

**Comment by mekya** [comment]
Hi @kputyra ,

Thank you for the issue. I understand what the problem is.  Appreciate the way how you report the issue. Thank you again.

In some cases, yeah it may take a few seconds(maybe a few hundred of milliseconds) to make the stream fully available in all interfaces. 

What I recommend is that you can ask the server to get stream information through websocket. 
When server returns with stream information, you can start playing. 

Ask the stream info like this
```
webRTCAdaptor.getStreamInfo(streamId);
```
https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/play.html#L412

if server returns streamInformation, try playing
```
webRTCAdaptor.play(streamId, token, subscriberId, subscriberCode);
```
https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/play.html#L400


Does that create a solution for you?

Regards,
A. Oguz

**Comment by kputyra** [comment]
Hi @mekya ,

Thank you for your reply.

Do I understand correctly that when the web hook receives the liveStreamStarted notification, then (in case of RTMP stream) the HLS stream is ready, but WebRTC not yet? In our case it takes sometimes 15sec and more before the stream is ready for WebRTC.

In our project streams are very dynamic and we have an additional layer on top of Ant Media that controls the streams. A publishing client announces a stream but does not publish it until requested to do so by another peer. The controller layer is responsible for checking whether a requesting client can play a stream, providing streaming ids and tokens, notifying a publisher client that a stream has been requested and notifying a requesting client when a stream is ready to play.

The quick solution you propose works, but leads to another issues - we no longer trust the response from Ant Media. Perhaps it is worth to change the error message from 'no_stream_exists' to 'stream_not_ready' in that case. Then we could distinguish between this case (a stream is in preparation) and when there is no stream, because publishing has failed (so that there's no reason to further fetching the stream). As for now I can cross-examine the 'no_stream_exists' error with a REST API call every several seconds.

Regards

**Comment by mekya** [comment]
Hi @kputyra ,

I see your point. HLS stream may take some more time ready because of its nature. 
For the RTMP ingesting, webhook is fired whenever Ant Media Server get the first bytes for RTMP ingesting. 

I've just studied the code a little and I think yeah we can fire the webhook when the preparing stuff is done. So that when it's called WebRTC stream is available.  

Thank you for the report.
