### ISSUE TITLE
Investigate to play S3 VoD files in play.html page 

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#3235]
### Short description
I have tried to play uploaded S3 videos on the embedded player page(play.html). I couldn't achieve to play. It gives below error:
```
Access to fetch at 'https://xxxxx.s3.eu-central-1.amazonaws.com/streams/stream1_3.mp4' (redirected from 'https://amsServerURL:5443/LiveApp/streams/stream1_3.mp4') from origin 'https://ovh36.antmedia.io:5443' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
fetch.stream.js:61 HEAD https://xxxxx.s3.eu-central-1.amazonaws.com/streams/stream1_3.mp4 net::ERR_FAILED
tryToVODPlay @ fetch.stream.js:61
(anonymous) @ play.html?name=stream1_3&playOrder=vod:518
fetch.stream.js:91 Error: TypeError: Failed to fetch
```

What I tried:
- I checked video properties, it's public. Bucket is public as well.
- Tried with latest videojs and http-streaming js files.
- Added CORS details to S3 bucket CORS details according to this doc -> https://docs.aws.amazon.com/AmazonS3/latest/userguide/ManageCorsUsing.html

### Environment
* Ant Media Server version: v2.3.2

### Steps to reproduce
1. Add S3 details to Ant Media Server configs, Add HttpForwarding details as well.
2. Publish stream and check mp4 record is in S3 bucket.
3. Try to play the uploaded stream via play.html page.

### Expected behavior
I'm expecting it should work.

### Actual behavior
Player doesn't play.

### Logs
I already added error log on above issue details.

**Comment by cemklc** [comment]
Hi,

**This issue is fixed by configuring CORS parameters on AWS S3 Bucket Permissions**

This issue is caused If you don’t control the server that you send a request from your browser, and the server needs an Access-Control-Allow-Origin header.

To fix the issue, CORS parameters of AWS S3 bucket should be modified so that the requests that are coming from another origins can be processed.


Go to your AWS -> Services -> S3 -> Buckets -> "Your Bucket" -> Permissions -> 
And at the bottom of the page there is

 "Cross-origin resource sharing (CORS)
The CORS configuration, written in JSON, defines a way for client web applications that are loaded in one domain to interact with resources in a different domain."


Click Edit-> and paste the code provided below:
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "HEAD",
            "GET",
            "PUT",
            "POST",
            "DELETE"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]
```
"*" on the origin field can be changed for allowing permissions for exact origins, such as "http://www.your-domain.com" since you only want to accept requests that are coming from your end.


Some of the examples can be found from the link that is given in the first post and here;

https://docs.aws.amazon.com/AmazonS3/latest/userguide/enabling-cors-examples.html
