### ISSUE TITLE
Investigate Lip Sync Issue in 2.3.2

### ISSUE THREAD

**Issue by DespicableSensei** [ant-media/Ant-Media-Server#3262]
### Short description
A customer has reported that they have faced lip syncing issues in both the community and enterprise edition. Reinvestigate.

### Environment

* Operating system and version: ? 
* Java version: ?
* Ant Media Server version: 2.3.2
* Browser name and version: ?

### Steps to reproduce
1. Faced when resource usage is high.
 

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by burak-58** [comment]
Hi @DespicableSensei ,
We have some fixes about this issue. I want to verify if it is also fixed for your case.
Could you please give me some more information about the use case? I guess you are publishing with WebRTC and playing with HLS since you also meet the issue in the community edition. But I want to be sure.

**Comment by sudeepdbg** [comment]
Yes we are ingesting webrtc and distributing with HLS.

**Comment by burak-58** [comment]
Please try it v2.3.3 which has been just released.
