### ISSUE TITLE
CORS filter issue

### ISSUE THREAD

**Issue by fatih2284** [ant-media/Ant-Media-Server#3272]
### Short description
Even if I entered the CORS filter settings in the "/usr/local/antmedia/webapps/root/WEB-INF/web.xml" file still I am getting (Access to XMLHttpRequest at 'rtmp://10.7.10.38/LiveApp/202169874785808765627933' from origin 'http://10.7.10.50' has been blocked by CORS policy:) error in the browser, is there any other settings related to CORS policy or am I missing something?

	<filter>
		<filter-name>CorsFilter</filter-name>
		<filter-class>io.antmedia.filter.CorsHeaderFilter</filter-class>
		<init-param>
		  <param-name>cors.allowed.origins</param-name>
		  <param-value>http://10.7.10.50</param-value>
		</init-param>
		<init-param>
		  <param-name>cors.allowed.methods</param-name>
		  <param-value>GET,POST,HEAD,OPTIONS,PUT,DELETE</param-value>
		</init-param>
	</filter>
	<filter-mapping>
		<filter-name>CorsFilter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>
	

### Environment

* Operating system and version: Ubuntu 20.4
* Java version: openjdk version "11.0.11"
* Ant Media Server version: 2.2.1
* Browser name and version: Chrome 90.0.4430

### Steps to reproduce
1. 
2. 
3.

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
Access to XMLHttpRequest at 'rtmp://10.7.10.38/LiveApp/202169874785808765627933' from origin 'http://10.7.10.50' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by SelimEmre** [comment]
Hi @fatih2284,

As I saw, you are using RTMP protocol in Google Chrome. Google Chrome doesn't allow using RTMP protocol. Also we don't recommend using RTMP playback. You can use HLS or CMAF(LL-DASH) methods instead of RTMP playback.

Please check below guides for more detail:​
https://github.com/ant-media/Ant-Media-Server/wiki/HLS-Playing
https://github.com/ant-media/Ant-Media-Server/wiki/Embedded-Web-Player
https://github.com/ant-media/Ant-Media-Server/wiki/How-to-use-CMAF%3F
