### ISSUE TITLE
I want to perfect websocket signaling command / notification / error message reference.

### ISSUE THREAD

**Issue by gtk2k** [ant-media/Ant-Media-Server#3293]
I want to perfect websocket signaling command / notification / error message reference.
Wiki is not perfect.

**Comment by mekya** [comment]
Hi @gtk2k ,

We can check the references. Let us know the parts are missing.

**Comment by eneskuluk** [comment]
Hi @gtk2k ,
I have added the missing ones and updated the currents ones.
Could you check if something you are looking is missing?

**Comment by kputyra** [comment]
@eneskuluk @gtk2k 
The reference does not explain some parameters in a few places.
1. It would be worth to add references to a blog/doc explaining `subcriberId` and `subscriberCode`.
2. What is exactly `trackList` in the second step in **Playing WebRTC Stream** and how to use it? Does this parameter allow to start playing the stream with audio or video track disabled on start?
3. In **toggleVideo** and **toggleAudio** commands, is the parameter **trackId** mandatory in case of a single track stream?

On a side, I know the reference for 1, but I couldn't find for 2.

**Comment by gtk2k** [comment]
@eneskuluk
Where did you change the posted reference?

https://github.com/ant-media/Ant-Media-Server/wiki/WebRTC-WebSocket-Messaging-Referenc
e
Is there a reference to a WebSocket signaling message other than the GitHub Wiki?

If you are connecting only with a DataChannel, you need to set both the video and audio parameters to off. The GitHub Wiki doesn't have a description for this.

Also, the label parameter of the message sending Ice Candidate is
         Label: "$ {CANDIDATE.SDP_MLINE_INDEX}",
It is written. In other words, the explanation is to set the string type in the label parameter, but if you actually set the string type in the label parameter and send it, an error will occur. However, it must be set as a number.

**Comment by eneskuluk** [comment]
@kputyra Thanks for the feedback, I'll add more explanations according to your feedback
@gtk2k  I changed the one you referenced. 
About only datachannel, I thought this can be deduced by the users since if you remove the video and audio from webrtc connection, only datachannel remains. 
I'm not sure these flows should be in the websocket reference since this is only for websocket operations but let me explain them in here.
If you don't leave from the room and only stop the streaming, you will remain in the room.
I didn't get this question from you: `when adding / deleting a video stream (keeping the data channel connection) after joining only the data channel.`
Could you elaborate this one?
