### ISSUE TITLE
Configure the timeout value for deciding the user is disconnected

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#3358]
Scenario
1. User publish stream to the server
2. Network is disconnected or has some kind of connectivity issues
3. Ant Media Server reports that user is disconnected after about 5~(`timeout value`) seconds.

`timeout value` should be configurable.

**Comment by mekya** [comment]
This issue is also related to this one https://github.com/ant-media/Ant-Media-Server/issues/3181

**Comment by golgetahir** [comment]
For the next step of this issue consider this scenario:

1)Publisher connects to the server and starts publishing
2)Player connects to the server and starts playing
3)Publisher is disconnected from the internet
4)Stream stops since publisher is disconnected from the internet
5)Player also disconnects from the ICE connection since stream stops

Maybe we can continue the stream without video or audio for a while to let publisher reconnect, meanwhile if the publisher reconnects, the player will be already connected and continue from there.
