### ISSUE TITLE
PoSt requeSt in antmedia

### ISSUE THREAD

**Issue by varunsdcet** [ant-media/Ant-Media-Server#3366]
Hi 
I am joining to the conference using REST API
URL : https://mydomain.com:5443/LiveApp/rest/v2/broadcasts/conference-rooms/broadcast1624335583025/add
I am requesting by this json
{
    "room_id":"broadcast1624335583025",
    "streamId":"kdnttttt"
}

but i get this message response :
{
    "success": false,
    "message": null,
    "dataId": null,
    "errorId": 0
}
What's the meaning of this response and what's wrong in this..
as i am already initialize room conference

**Comment by yashtandon113** [comment]
Hi @varunsdcet 
This issue was in our issue tracing system and is fixed by our team.
https://github.com/ant-media/Ant-Media-Server/issues/3281

But as conveyed over support side. Adding predefined stream to conference room feature is not included in the current latest version 2.3.3.1 and will be available in the v2.4.
You can also refer to below link
https://github.com/ant-media/Ant-Media-Server/pull/3294

I hope this will help.
