### ISSUE TITLE
WebRTC client missing

### ISSUE THREAD

**Issue by tehseensagar** [ant-media/Ant-Media-Server#34]
I could not find the webrtc client for android in source. I want low latency , RTMP having 30 sec delay . if it can be fine tune so let me know. 

Regards
 Tehseen

**Comment by mekya** [comment]
Hi Tehseen,
Low latency is in enterprise edition and WebRTC client for Android is not public. Anyway I can share it with you if you want to try.

Regards,
A. Oguz

**Comment by tehseensagar** [comment]
@mekya I would love to give it a try. could you please share it , tehseensagarpk@hotmail.com .

Further more could you please tell me how do I reduce detail if I go with RTMP its 30sec delay in it.

Regards

**Comment by mekya** [comment]
Hi @tehseensagar ,
I've sent the trial version to your e-mail address. 

In order to reduce latency in HLS, make sure that key frame interval is about to 2 seconds in your encoder and in web panel again make sure that server hls segment time 2 seconds, list size 5 
Then latency will be about 8-10 seconds in HLS.

In WebRTC solution, WebRTC-to-WebRTC latency is about 0.5 sec. WebRTC-to-HLS latency is again can 8-10 seconds. 

Closing this issue, please reopen it if you have further questions or problems.

**Comment by dariush-fathie** [comment]
@mekya i want to try android native webRTC . could you send it to me to ?
dariush.fathe@gmail.com

thank you
