### ISSUE TITLE
Origin and Edge mode in Kubernetes cluster

### ISSUE THREAD

**Issue by khanhvu161188** [ant-media/Ant-Media-Server#3402]
I have follow the tutorial to install ant media pods onto my k8s cluster along with the ingress but I don't really know how to separate 2 different groups for **Origin** and **Edge**?
1 solution that I can think about is deploying in 2 different namespaces with domain1.example.com for publisher(**Origin** group) and domain2.example.com for viewer(**Edge** group) but I am not quite sure whether the pod in Edge group could reach the pod in Origin group cause they are in 2 different namespaces.

Could you @mekya please check it?
Thanks

**Comment by mekya** [comment]
Hi @khanhvu161188 ,

I'm so sorry. I've missed this issue to respond because of the workload.

Let me give my comment.  It seems that namespaces create a solution for that. Alternatively, using two services may be also another solution. One service for origins and other service for edges.

Because of the nature of the WebRTC, Ant Media Server uses host network and use the real ip address of the worker node. I don't think there will be a problem between origin and edge nodes connectivity unless there is no other firewall rules.
