### ISSUE TITLE
Trouble with WebRTC iOS SDK when using Bluetooth device

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/Ant-Media-Server#3409]
One of our clients reported this issue. Here are the details:

> When I connect Bluetooth first and after that I join conference room by WebRTC, I don’t hear anything sound.
> After that I disconnect Bluetooth and connect Bluetooth again then I can hear.
> Or switch to speaker and switch again Bluetooth then I can hear.

Re-produce scenario 
1. connect Bluetooth first and after join the conference

Expected behavior
Hearing the sound in the conference room through bluetooth headphone

Actual behaviour
No sound in the bluetooth headphone. Sound is coming from iphone. 
Re-connecting the bluetooth headphone fixes this issue.  Switch to speaker and switch again Bluetooth then I can hear.

**Comment by mekya** [comment]
Hi,

I've just tested this case. I've connected my bluetooth headphone in advance and started the sample application to join the conference. 

I can hear the people in the call through headphone. I also tested one of my colleague. 

I think maybe it's a configuration issue on your end because you're changing the audio configuration in your app.

We can again schedule a call to discuss and test about it.
