### ISSUE TITLE
Removing the camera acess when we call turnofflocalcamera 

### ISSUE THREAD

**Issue by geethaharika** [ant-media/Ant-Media-Server#3420]
When we turn off a camera my camera access(which is the white light near the camera is still on). So when I implement the feature from my side I have to remove the video tracks republish them every time when the user switches the camera to make it correctly but it is not the correct way to do it. 

It's better we are still able to toggle video even when the constraints updated through the open stream. my video is not getting published when I update constraints after publishing.

When the user switches the camera I am removing the video tracks in order to close the camera access light and trying to re-publish with updated constraints.

**Comment by tkdave** [comment]
To update constraints, you will want to make a new mediastream, remove old tracks from existing stream, and then add tracks from the new stream to the old stream. Keep using the old stream.

I'm using a function that looks like this:
```
// update all tracks (audio and video)
export const updateTracks = (localStream, newStream, onEndedCallback) => {
  // remove old tracks from local stream
  localStream?.getTracks().forEach((track) => {
    localStream?.removeTrack(track)
    track.stop()
  })

  // add new tracks to local stream
  newStream?.getTracks().forEach((track) => {
    localStream?.addTrack(track)
    if (onEndedCallback != null) {
      track.onended = function (event) {
        onEndedCallback(event)
      }
    }
  })
}
```

You may also need to store and update the enabled state on the tracks.

My use case requires accessing the camera in multiple places, so I am managing clones of a main mediastream and then using those. This is due to mobile webkit limitations around calling getUserMedia more than once.

My request for antmedia folks would be to better support external stream management, as the webrtc adaptor code is making a lot of assumptions that we are all having to code around.

**Comment by golgetahir** [comment]
Hi @tkdave 

Can you elaborate your request, maybe giving an example case?

Cheers.

**Comment by tkdave** [comment]
In our app, we have a user input settings popup that gives you a preview of the selected camera feed. There you can change mic and camera inputs, test the mic, test the camera, etc. We show this to the user before they enter chat, but people often use this while they are in the chat room. Now we have multiple videos on the screen each showing the same camera feed. This requires multiple calls to getUserMedia.

Here is the issue:
https://bugs.webkit.org/show_bug.cgi?id=179363

On iPhones, the second call to getUserMedia fails.

Also, in some browsers, new getUserMedia calls result in extra permissions request popups.

The best practice is to call getUserMedia only when absolutely necessary (when selected inputs change) and to clone the media stream when you need to use it. In our app, we have a UserMediaService that manages named getUserMedia requests and hands out clones that I then attach to a local video preview or to an ant webrtc adaptor for publishing.

But, main point in this thread was how to turn off camera light. The answer is to stop all tracks on local stream, as the ant media example webrtc_adaptor does, but this requires strict management of media streams in more complex apps.

For us, we ended up managing device listeners and calls to getUserMedia in separate services. To make this work with webrtc_adaptor, I needed to have it create its localVideo on demand (not pull from ID on page), and then (to answer @geethaharika), whenever we update the stream, I tell webrtc_adaptor about the change using the `gotStream` method.

I see that gotStream now checks for presence of localVideo. This was one issue I had seen. The only "assumption" I would like to see changed is how localVideo is created. Would be nice to have a clean way to pass that in or to have it created (`document.createElement('video')`) when needed. Ideally, you track the video element and let me add it to the DOM when needed instead of assuming I have some video holder ready to go. `gotStream` works for me for passing in my user media. Maybe there is a cleaner path. 

And, of course, after all that, every now and then that camera light stays on. They are the worst.

**Comment by golgetahir** [comment]
Hi people,

I have come up with a solution for the camera light issue by replaceTrack property of webrtc, created a dummy stream for a frame long and replaced it with the camera stream to keep connection intact while sending 0 frames or bytes. By this way the camera is released and light goes off. Please check the above mentioned PR.

@tkdave As a first step I resolved camera light on off issue if that works for you, for the further development suggestions, can you please create another issue for them explaining your requirement if that is possible to not get distracted and stay focused on one thing at a time?

Cheers.
