### ISSUE TITLE
Cannot play/download VOD from another node in Cluster

### ISSUE THREAD

**Issue by jainnaman16** [ant-media/Ant-Media-Server#3485]
### Short description
In cluster mode, we are unable to download or play the mp4 VOD videos from another node. The publishing node is generating and saving the mp4 VOD and we are able to play or download it via the origin node only. When we try to access it from some other node, it throws Error 404. 

### Environment
* Operating system and version: Ubuntu 18.04.5
* Java version:  11
* Ant Media Server version: 2.3.3
* Browser name and version: Chrome 91.0.4472.114

### Steps to reproduce
1.  Start Ant Media in cluster mode with two or more nodes
2. Complete a live stream and wait for VOD to be generated / Upload a VOD on server 1
3. Open dashboard for another server and play generated/uploaded VOD. 

### Expected behavior
We should be able to play the VOD from any server's dashboard. 
We should be able to download the VOD from any server. (http://<SERVER_NAME>:5080/LiveApp/streams/<STREAM_ID>.mp4)

### Actual behavior
Throws Error 404 on pressing the play button. 
Throws Error 404 on downloading the VOD mp4 (http://<SERVER_NAME>:5080/LiveApp/streams/<STREAM_ID>.mp4) 

 
### Logs
No Logs regarding this available in ant-media-server.log file. No logs in antmedia-error.log 

 Is this expected behaviour even in clustering?

**Comment by mekya** [comment]
Hi @jainnaman16 ,

Thank you for the issue. 

Yeah this is an expected behaviour in clustering. Fortunately, there are a couple of solutions for that. 

1. Create a distributed file system with GFS. (https://en.wikipedia.org/wiki/Google_File_System)
2. Use a storage such as S3 to store video files and forward the incoming requests to the S3 through Ant Media Server

Ant Media Server can upload the recorded files to S3 automatically. 
https://github.com/ant-media/Ant-Media-Server/wiki/How-to-record-streams-to-s3-compatible-systems

You can even forward the incoming requests to the S3
https://github.com/ant-media/Ant-Media-Server/wiki/HTTP-Forwarding

Please check it and let me know if I can help further. 

Regards,
A. Oguz

**Comment by jainnaman16** [comment]
Hi @mekya ,
Apologies for the delayed response. 

Thank you for your input. We are going forward with the S3 solution. We'll let you know in case we face any other issue in future. 

Regards,
Naman

**Comment by mekya** [comment]
No worries :)

My pleasure

Take care
