### ISSUE TITLE
Stream is not working using hash based token in v2.4 with AWS cloud front.

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#3628]
### Short description
Stream is not working with hash based token in v2.4 with aws cloud front but is working fine with previous version 2.3.3.1.

### Environment
* Operating system and version: ubuntu 20.04
* Ant Media Server version: v2.4.0.2
* Browser name and version: chrome 93.0.4577.63

### Steps to reproduce
1. Install AMS v2.4.0.2
2. Enable publish and play with hash token settings in red5-web.properties
3. Configure cloud front distribution following https://antmedia.io/publish-hls-stream-cloudfront-with-ant-media-server/
4. For cache settings please refer this issue https://github.com/ant-media/Ant-Media-Server/issues/3463

### Expected behavior
Stream should work fine with cloud front URL.

### Actual behavior
Stream is not working and giving 403 error

### Logs
https://pastebin.com/ecLHMhFr

**Comment by adisahu1989** [comment]
Hi is there any timeline decided to release this bug.

**Comment by mekya** [comment]
Actually, it's not a bug. 

@burak-58 , could you please explain the status and provide a workaround?

**Comment by burak-58** [comment]
Hi @adisahu1989,
Let me mention the difference between v2.3.3.1 and v2.4.0.2 first.
With the following commit we started to check token for all requests to files in streams directory.
https://github.com/ant-media/StreamApp/commit/e4ad51a4c32cbed5fa4366c4ba2dded821df8523#diff-f1c1b2e33984786db489cb4229fb7610cabae6dc83df075488c9e1236a91268c

If you use play.html there is no problem because it makes ts queries also with token. But if you want to play the stream with m3u8 URL+token, then you should also guarantee to request ts files with the token.

Lastly, if you make all requests through the same session then passing the token once is enough. I mean if you make m3u8 request with token and make ts requests without token but with the same session, then you can play. But CloudFront changes the session for each request so it doesn't work.

**Comment by mekya** [comment]
Maybe we can also provide a workaround solution for the limited security so that it will work with the same way as in the older version? @burak-58 

As far as I know, it's just editing the web.xml file and users may try by knowing the limited security.

**Comment by burak-58** [comment]
The _web.xml_ file is located in _/usr/local/antmedia/webapps/{APP_NAME}/WEB-INF/_ folder in the server.
To make it work as in 2.3.3.1 version, you can change the `<url-pattern>` fields for `<filter-mapping>` as excluding _.ts_ files.
You can replace `/streams/*` with `/streams/*.m3u8` and you can add url pattern for mp4 or other file types.

As an example you can check this:
https://github.com/ant-media/StreamApp/blob/7c9bd619e396b13a754b14d6315c5e0e39bf4839/src/main/webapp/WEB-INF/web.xml#L35
