### ISSUE TITLE
HLS(.m3u8) not playing with JWT stream token in v2.4.0.2

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#3720]
### Short description
HLS with .m3u8 is not playing with the JWT stream token in latest v2.4.0.2 while it is working fine in v2.3.3.1.

### Environment
* Ant Media Server version: v2.4.0.2

### Steps to reproduce
1. Enable play with JWT stream token 
2. Try to play .m3u8 stream with generated token 

### Expected behavior
The stream should play with token.

### Actual behavior
Stream is not playing with token.

**Comment by golgetahir** [comment]
Hi all,

Let me explain the situation here;

When you are requesting the m3u8 file from the server, you should also request the ts files since the video is inside them and that is how hls working. If you request the files from any other 3rd party application rather than our play.html's videoJs, the third party application should send each request to the server with token for security. Some applications including VLC, when you give it a link like: https://test.test:5443/LiveApp/streams/stream2.m3u8?token=eyJhbGciOiJIUzI1NiJ[…]iJwbGF5In0.EQad96MUhCsWbGHHciHh23XAh7qsEHFDBkVwdVmX3x0 it will add the ?token=<> part to only m3u8 request and while they requesting the ts files they don't append the token, thus the data can't be retrieved. Please either use videoJs with our implementation or configure your player to send request with tokens. Older versions simply does not have this security implementation.

Cheers

**Comment by haonv206** [comment]
Hello @yashtandon113 
It's Sam, who asked you this issue via email.

@golgetahir 
I'm playing HLS stream on my mobile app using famous libraries (AVPlayer on iOS, ExoPlayer on Android), and I saw that all of them can't add the ?token=<> to the TS files automatically.

I must modify the m3u8 file content myself from server-side (add ?token to m3u8 content), using Nginx Substitutions.
For example, a m3u8 file like this:
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXTINF:10,
stream-1.ts
#EXTINF:10,
stream-2.ts
#EXT-X-ENDLIST

Should be replaced to:
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXTINF:10,
stream-1.ts?token=\<jwt-token-here\>
#EXTINF:10,
stream-2.ts?token=\<jwt-token-here\>
#EXT-X-ENDLIST

It works now, but I took me very long time to find out this issues, because there is no any official document on this.
