### ISSUE TITLE
Issue with VOD naming for same streamId when S3 recording is enabled

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#3739]
### Short description
When S3 recording is enabled and same streamID is used, the VODs on dashboard are getting saved without suffix.

### Environment

* Ant Media Server version: 2.3.3.1, 2.4.0.2

### Steps to reproduce
1. Enable S3 recording for live streams.
2. Use same streamID (e.g., stream1) and publish consecutive streams.
3. Check the VOD name on the AMS Dashboard and in the S3 bucket.

### Expected behavior
The VODs on the dashboard should have suffix in their name. e,g., stream1, stream1_1,stream1_2. etc.

### Actual behavior
The VODs on the dashboard have same stream name.
![VODs when S3 Enabled](https://user-images.githubusercontent.com/86982446/141493018-89cf0be7-47eb-4b35-9b69-60e7a6d17aab.png)

In S3 bucket, it's saving as expected (with suffix)
![s3 bucket](https://user-images.githubusercontent.com/86982446/141493370-6ba2f7af-3aec-46be-bd22-978d7a719737.png)

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by golgetahir** [comment]
Hi all,

Actually, this is an expected behavior since the VoDs are getting deleted from the local storage after they are uploaded to S3, dashboard is not being updated if you delete the VoDs from the streams folder. Anyway since there is confusion about hard coding the delete mechanism for mp4 files after the s3 upload, I have made it configurable from the /usr/local/antmedia/webapps/<app_name>/WEB-INF/red5-web.properties as the settings is;

settings.deleteFileAfterS3Upload

@mekya please see the below mentioned PR, thank you.

**Comment by mekya** [comment]
I've a change request on the server side. 

In addition,  I think the real problem is not about deleting the files after s3 upload. I mean this is not a good solution, it's like a patch or workaround solution. 

Please think a better solution.
