### ISSUE TITLE
Can't play RTMP from AMS cluster

### ISSUE THREAD

**Issue by yossidar** [ant-media/Ant-Media-Server#3770]
### Short description
I have 2 AMSs defined as cluster. I publish RTMP stream to AMS-A and try to play it by reaching out AMS-B.
When I try to play webrtc - it works.
When I try to play rtmp (with ffplay) - it doesn't work.

### Environment
AMS 2.4.0.2 on ubuntu 18

### Expected behavior
Be able to play rtmp with cluster mode if the request reaches non-origin server

### Actual behavior
Can't play rtmp.
 
Thanks
Yossi.D

**Comment by yossidar** [comment]
In other words, is it possible to consume rtmp from edge server?

**Comment by yashtandon113** [comment]
Hi @yossidar 
Ant Media Server can ingest RTMP and that RTMP stream can be watched through edge servers with HLS, WebRTC, CMAF
But it cannot be played with RTMP from edge servers as it is not supported. You can play it from the same origin node if you want.
It's not supported because RTMP playback is dying or already dead. We provide several other options to playback in the cluster. CMAF(3-5 secs), HLS(8-12 secs), WebRTC(<0.5 secs)

**Comment by yossidar** [comment]
Thanks for the detailed answer.
