### ISSUE TITLE
Installation on Ubuntu 20.04.2 ARM

### ISSUE THREAD

**Issue by Molnfront** [ant-media/Ant-Media-Server#3945]
### Short description
Run the installation script. 

### Environment

* Operating system and version: Ubuntu 20.04.2 ARM
* Java version:  N/A
* Ant Media Server version: latest enterprise version
* Browser name and version: null

### Steps to reproduce
1. Run the script
2. Watch terminal
3. See the bug

### Expected behavior
A nice installation of AMS 

### Actual behavior
E: Version '11.0.2+1-1~18.04.2' for 'openjfx' was not found
E: Version '11.0.2+1-1~18.04.2' for 'libopenjfx-java' was not found
E: Version '11.0.2+1-1~18.04.2' for 'libopenjfx-jni' was not found
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.

When I look at it now I can probably fix it by finding the right versions for Ubuntu 20.04.2 ARM if they exists..
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
You're great @Molnfront to let us have such a great issue. It exactly make sense. 

For a quick workaround, I may recommend to remove the related lines in install script about libopenjfx. Because they are related to the built-in object detection. We maintain the object detection as a plugin. 

I'm happy to move it to the backlog and schedule it. It'll be scheduled likely in next week. 

Thank you @Molnfront

**Comment by mekya** [comment]
The PR has been merged.  Thank you @muratugureminoglu 

Btw, tensorflow plugin works when it's installed with [install_tensorflow_plugin.sh](https://github.com/ant-media/Ant-Media-Server/blob/master/src/main/server/install_tensorflow_plugin.sh) script?
