### ISSUE TITLE
Allow selection of onvif url provided from camera

### ISSUE THREAD

**Issue by gmonk** [ant-media/Ant-Media-Server#4157]
**Is your feature request related to a problem? Please describe.**
Siqura PTZ Camera  HSD626 provides 4 different encoders 1-4 first two  only encoders 3-4 support H.264
antmedia does not properly detect all encoders and give option to select it will only detect Profile_1  I have tried to override by providing ONVIF URL with Profile_3  but antmedia does not honor the entry and once saved still seems overwrite and url changes back to Profile_1
**Describe the solution you'd like**o
Using other VMS type software on the same camera the ONVIF probe will return list of rtsp urls from the camera and give you the option to select proper url. This would be a nice option.

**Describe alternatives you've considered**

**Additional context**

**Comment by mekya** [comment]
Thank you for the issue @gmonk ,

I'm moving to the backlog to schedule it.

**Comment by gmonk** [comment]
Are there any work arounds to force the onvif url ? do these configs get stored in a config file or database ?  I am trying to demo this with the hopes of being able to purchase the enterprise version but if it does not work with our CCTV cameras I do not have much to go on. 

Thanks

**Comment by mekya** [comment]
Hi @gmonk ,

These configs are stores in database. After server gets the RTSP url, it saves to the DB and you can change the RTSP URL in the db. It's a little tricky. 

I think the support team can help you if you go to Enterprise edition. You can reach to support via support@antmedia.io
You can also mention this issue in the support channel. 

Please let me know if I can help with anything

**Comment by gmonk** [comment]
This issue is still prevalent in the latest release.  I believe the interpretation of what I was talking about was way off.  This is not an issue with simply being able to query the profiles to a camera that has been already added via REST.  The issue is when trying to add any current CCTV camera capable of multiple encoders which is the majority of enterprise CCTV cameras out there.  When trying to add any one of these cameras  Antmedia simply adds the first profile it finds assuming thats the right profile when in fact several cameras will use different codecs for different profiles such as mjpeg or mpeg4  which is the case for the cameras we use the encoders 1&2 are both mpeg4 which ant media does not seem to decode and 3&4 are H.264   But Antmedia simply chooses ProfileToken_1_1 every single time.  This can easily be fixed by either probing the ONVIF media params in the camera and returning an option for the user to select from before adding or simply honor the url given by the user when manually adding.  I have tried to add the correct profile or edit an existing profile and change it to ProfileToken_1_3  but no matter what Antmedia simply rewrites it backto ProfileToken_1_1 or re-probes the camera picking the first profile and does not accept the changes 
![2022-11-09 15_55_42-Device McQueen_Elliot (10 96 30 198) ONVIF parameters](https://user-images.githubusercontent.com/4925164/200961688-de06d66e-5022-4f20-95f9-a6603f50dadd.png)

![2022-11-09 15_51_10-10 96 30 198_frame html](https://user-images.githubusercontent.com/4925164/200959217-d5a4cb06-25ed-471a-a6ed-bd173991ce96.png)

**Comment by mekya** [comment]
Hi @gmonk ,

Thank you for your comment.  You point out different angle and it makes sense. 

Anyway, just let me tell what the current solution works and then discuss a solution for your case. 

We thought that user can choose any profile to change resolution and bitrate so that we created a REST method to let the user get the profiles. Here is the basic workflow

1. Get the RTSP Stream URLs from the [device with this REST method](https://antmedia.io/rest/#/BroadcastRestService/getOnvifDeviceProfiles). (I think we can refactor the name because method does not match its function. )
2.  Update the the broadcast streamUrl with [this REST method](https://antmedia.io/rest/#/BroadcastRestService/updateBroadcast)

In this way, you can use any RTSP Stream URL on the device. Please let me know if it's a solution for you. 

Secondly,
I agree that Ant Media Server should pull the first compatible Stream profile(H264) by default and let the user choose the other profiles. The solution above provide the ability to let the user choose the other profiles programmatically. I guess you want this ability to be available on the web panel?

Lastly, I really would love to see what you've developed and understand how we can help you each other. Is it possible to schedule a meeting and discuss further about our collaboration?

**Comment by gmonk** [comment]
Just curious was this ever implemented ?
