### ISSUE TITLE
HLS manifest gives 404 on Edge node in cluster when subfolder is created under streams directory.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#4221]
### Short description
In a cluster when a subfolder is created under streams directory for a broadcast, HLS manifest is not playing from the edge node and webrtc also fails to load.
Both play fine on the origin node hosting the broadcast.

### Environment

* Ant Media Server version: v2.4.3

### Steps to reproduce
1. Create a broadcast using REST API or from dashbaord.
2. Update the subFolder for the broadcast.
3. Play HLS manifest from the edge node.

### Expected behavior
HLS manifest should play fine from the edge node.

### Actual behavior
HLS manifest fails to load and gives 404, even WebRTC failes to load on edge node.

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Hey Guys,

This problem has been fixed in v2.5.0.  Here is the [2.5.0 changelog](https://github.com/ant-media/Ant-Media-Server/releases/tag/ams-v2.5.0)

Just a point that you need to give subfolder in the m3u8 url. For instance, if the subfolder is `classroom` and the stream id is `stream1` for `LiveApp`. You need to access the m3u8 through this url `https://{FQDN}/LiveApp/streams/classroom/stream1.m3u8`
If you're using embedded player, you can give `classroom/stream1` as `id` parameter in the url. 

FYI

@dalv0911 and @LeDoTruongAn
