### ISSUE TITLE
Playlist does not play continuously

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4226]
### Short description
1. The loading time between two mp4 files is high in playlist.
2. Next mp4 file in a playlist is not loading when playing the stream with m3u8.
3. No scroll bar in playlist GUI

### Environment
* Ant Media Server version: v2.4.3 & above

### Steps to reproduce
**Issue 1**
1. Create the playlist with 2 mp4 URLs
2. Play the stream with WebRTC
3. Check the loading time between 2 mp4 files

**Issue 2**
1. Create the playlist with 2 mp4 URLs
2. Play the stream with m3u8 URL

**Issue 3**
https://github.com/ant-media/Ant-Media-Server/issues/4197

### Expected behavior
For Issue 1- Loading time should be less
For Issue 2- 2nd mp4 file should load after 1st one is finished

### Actual behavior
For Issue 1- Loading time is high (approx. 4-5 sec)
For Issue 2- 2nd mp4 file is not loading

**Comment by mekya** [comment]
Hi @yashtandon113, @LeDoTruongAn and @ekrem-pinar 

I've just a quick look for this issue because users in the community are having difficulty for this issue. 

Let me explain the best practices for that. I hope it helps. 

Issue 1: It does not make sense to play the stream with WebRTC because it's already recorded file and there is no ultra low latency requirement. It make sense to play the stream with HLS.  Just keep in mind that WebRTC playback uses more processing resources than the HLS.  Even if you would like to decrease the amount of time to switch streams,  please read the followings 

Firstly
- Open the embedded player(/usr/local/antmedia/webapps/{YOUR_APP}/play.html`)
- Find the `genericCallback` method and decrease the timeout value 3000 to 1000 or even lower at the end of the `genericCallback` method. [It's exactly this line](https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/play.html#L261)

Secondly,
- Decrease the key frame interval of the video. You can set to 1 seconds. Generally recommend value is 2 seconds.  WebRTC needs key frame to start the play. If the key frame interval is 10 seconds(default in ffmpeg), player may wait up to 10 seconds to play 

Issue 2:    
Yes, this is the point. Please do the following things to have a very smooth experience

1. Open the properties file of the application -> `/usr/local/antmedia/webapps/{YOUR_APP}/WEB-INF/red5-web.properties`
2. Add the following property 
   ```
   settings.hlsflags=delete_segments+append_list+omit_endlist
   ```
   Let me explain what it means. 
     - `delete_segments` just deletes the segment files that is out of the list so that your disk will not get full.
     -  `append_list` just adds the new segment files to the older m3u8 file so that player thinks that it's just playing the same stream
     - `omit_endlist` disables writing the `EXT-X-ENDLIST` to the end of the file so player thinks that new segments are in their way and it wait for them. It does not run stopping the stream
3. Disable deleting hls files on ended to not encounter any race condition. Continue editing the file  `/usr/local/antmedia/webapps/{YOUR_APP}/WEB-INF/red5-web.properties` and replace the following line 
`settings.deleteHLSFilesOnEnded=true` with this one

  ```
  settings.deleteHLSFilesOnEnded=false
  ```

 
Issue 3:
It's a front-end issue. Let us resolve that in a sprint.  Quick workaround solution can be using the REST API to add/remove items to the playlist.
