### ISSUE TITLE
Android SDK screen sharing issues

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4266]
### Short description
**Issue 1 -->** Screen share is not working on Android (11,12) and app is crashing after trying multiple times.
**Issue 2 -->** Built the Android SDK (on Android v10 or below) with screenshare activity but after doing screen sharing multiple times sample application is crashing.

### Environment
* Ant Media Server version: v2.4.3

### Steps to reproduce
1. Build the sample app with screen share activity
2. Select screen share option and publish the stream
3. Stop the stream
4. Try to start the stream again
5. App minimized itself
6. Open app and start publishing again
7. Stop stream
8. Try to start stream again then app crashes.

### Expected behavior
Issue 1 --> Screen share should work and app should not crash.
Issue 2 --> Application should not crash after multiple attempts.

### Actual behavior
Issue 1--> After giving permission for screen share, app minimizes at first time and crashed at 2nd time
Issue 2--> App is crashing after multiple attempts.

**Comment by doggomir** [comment]
This issue still exists after the merge of branch 'm85_update_nexteducation' (see https://github.com/ant-media/Ant-Media-Server/issues/4314)

The screen capture example crashes on Android 10, 11, 12 with the following error message:
`     Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION`

**Comment by mekya** [comment]
Thank you so much by giving this exception. Increasing its order in the backlog. 
 
Btw, I think there is a simple solution for that. It's likely the solution is available after some googling. If there is a developer on your side and can make a PR for this. It's highly appreciated. 
   
Thank you
