### ISSUE TITLE
First update the example with latest ant media version

### ISSUE THREAD

**Issue by saswat-pcode** [ant-media/Ant-Media-Server#4461]
### Short description
__Brief description of what happened__

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version:
* Browser name and version:

### Steps to reproduce
1. 
2. 
3.

### Expected behavior
__Put as much detail here as possible__

### Actual behavior
__Put as much detail here as possible__

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by yashtandon113** [comment]
Hi @saswat-pcode
Thanks for creating the issue.
Could you please provide more information about the problem as it is unclear?

**Comment by yashtandon113** [comment]
@saswat-pcode 
Do you mean a sample html page that doesn't work? Could you please describe the issue in more detail?

**Comment by mekya** [comment]
Hey @yashtandon113 , 
I think you close the issue for the inactivity. Thank you.

Just would like to add something, Could you please add a note that you close the issue for the inactivity? So the users will easily understand that it's closed because we don't have any respond from the user. 

Thank you.
Regards

**Comment by yashtandon113** [comment]
@mekya sure

We have closed this issue for the inactivity.
