### ISSUE TITLE
Unsupported URL scheme 'https']

### ISSUE THREAD

**Issue by KHChanna** [ant-media/Ant-Media-Server#4518]
Hi, i am trying to do a play video stream via `https` on flutter app. but AntMediaFlutter throw exception 

`Closed by server [500 => WebSocketException: Unsupported URL scheme 'https']!`

then here is the connection status `HelperState.ConnectionClosed`.

here is simple code for me:
`
AntMediaFlutter.connect(
      //host
      (https://domain.live),
      //streamID
     4726761174396765461354252
      //roomID
      '',
      AntMediaType.Play,
      widget.userscreen,
      false,
      //onStateChange
      (HelperState state) {
        print('-----------------------------------------');
        print(state);
        print('-----------------------------------------');
)
`

i have read document guide on https://resources.antmedia.io/docs/flutter-sdk but not work for me. Thank you

**Comment by yashtandon113** [comment]
@KHChanna
Thanks for creating the issue.
In the SDK, use web socket URL instead of HTTPS URL. Your web socket URL will be something like this:

`ws://domain-or-IP:5080/App-Name/websocket
`

Also, kindly check out the following documentation for Flutter SDK --> https://resources.antmedia.io/docs/flutter-sdk

**Comment by yashtandon113** [comment]
Closing this issue. Please feel free to open if you have any questions.
