### ISSUE TITLE
Stream starts buffering when audio sends from the camera.

### ISSUE THREAD

**Issue by rajeshoodles** [ant-media/Ant-Media-Server#4588]
### Short description
Streams not buffering when we send only video and also have very low latency. However, when we are sending audio with the video in that case streams start buffering.

### Environment

* Operating system and version:  Ubuntu 18
* Java version: 8
* Ant Media Server version: Community Edition 2.4
* Browser name : Chrome( Also facing same issue with RTMP URL).

### Expected behavior
The stream should not buffer continuously with audio and video.

### Actual behavior
It stops when we send audio with the video.
 

### Logs

Console logs

xer.Mp4Muxer - cannot write video frame to muxer(056727936262422954182196_1.mp4). Pts: 34446292830 dts:34446292830  Error is No space left on device 
2022-11-18 13:50:16,219 [vert.x-worker-thread-8] WARN  io.antmedia.muxer.Mp4Muxer - cannot write video frame to muxer(056727936262422954182196_1.mp4). Pts: 34446295800 dts:34446295800  Error is No space left on device 

Error logs

[hls @ 0x7f3fd8183a00] pkt->duration = 0, maybe the hls segment duration will not precise
[hls @ 0x7f3fd8183a00] pkt->duration = 0, maybe the hls segment duration will not precise
[hls @ 0x7f3fd8183a00] pkt->duration = 0, maybe the hls segment duration will not precise
[hls @ 0x7f3fd8183a00] pkt->duration = 0, maybe the hls segment duration will not precise

Join [community.antmedia.io](https://community.antmedia.io) and be a part of Ant Media Server Community.

**Comment by yashtandon113** [comment]
Hi @rajeshoodles
As per initial logs that you have sent, it seems there is no disk space left on your server due to which stream is not working as expected.

xer.Mp4Muxer - cannot write video frame to muxer(056727936262422954182196_1.mp4). Pts: 34446292830 dts:34446292830 Error is **No space left on device**
2022-11-18 13:50:16,219 [vert.x-worker-thread-8] WARN io.antmedia.muxer.Mp4Muxer - cannot write video frame to muxer(056727936262422954182196_1.mp4). Pts: 34446295800 dts:34446295800 Error is **No space left on device**

Also we recommend to use Java version 11 with Ubuntu 20.04.

Additionally you can upgrade your server to the latest v2.5.1. To upgrade your server, check out the following link:
https://resources.antmedia.io/docs/upgrade-ams

**Comment by rajeshoodles** [comment]
Hi @yashtandon113 
Ant Media server disk storage is filled by live stream files which are .ts files. I also enabled the setting _deleteHLSFilesOnEnded=true_, but the issue is streaming will not ever end in the future. Due to this, the .ts file is created on the server which consumes disk space. Could you please make a suggestion on how could I clear these .ts files?

**Comment by yashtandon113** [comment]
Hi @rajeshoodles 
Yes, it was a known issue in v2.4.3. You can check the following Git Hub issue for explanation: https://github.com/ant-media/Ant-Media-Server/issues/4196

This issue is completely resolved in v2.5.1. You can upgrade your server by following the link that I shared in my previous comment.
