### ISSUE TITLE
Investigate WebRTC Publishing not working properly on Safari

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#4615]
When trying to publish with WebRTC on Safari, it gives publish timeout error.

Ant Media Server Version: 2.5.1
Settings: H.264 enabled, 720p Adaptive Bitrate enabled, Dash disabled, HLS enabled.

**Comment by findgr** [comment]
A little info from our testing.

We started from basics. Clean install of a new ams 2.5.1 node and your mentioned settings.
Settings: H.264 enabled, 720p Adaptive Bitrate enabled, Dash disabled, HLS enabled.

We then went to https://your_domain_name:5443/WebRTCAppEE to publish and we get inconsistent results.

We kinda lack physical devices, but from the limited devices we used:

- _iPad 2017 iPadOS 16.1 Safari_: **Works**
- _iPhone 7 iOS 15.7.1 Safari_: Video OK, **NO** Audio.
- _iPhone 13 Pro iOS 16.1.1 Safari_ : Same, video ok, **NO** audio

Played back with the included player, both WebRTC and HLS streams.

On all the above devices we accept the camera and mic permissions.

Furthermore, we tested using Browserstack service:
They use physical devices, almost all cameras are covered or are in total darkness and we see a dark scene. On some we could make out something hanging on a wall.
On the audio side, the air conditioning in the data center is clearly audible, as well as bleeping sounds and phones ringing, so the mics pick up something.

We tested various devices and it seems to work, and doesn't work only of other unrelated issues, like expired Root Cert, or old Safari.
iPhone 14 (iOS 16) Safari - ok
iPhone 14 (iOS 16) Chrome - ok
iPhone 13 (iOS 15) Safari - ok
iPhone 13 (iOS 15) Chrome - ok
iPhone 12 (iOS 14) Safari - ok
iPhone 12 (iOS 14) Chrome - ok
iPhone 11 (iOS 13) Safari - ok
iPhone 11 (iOS 13) Chrome - no, but unrelated.
iPhone XS (iOS 12) Safari - ok
iPhone XS (iOS 12) Chrome - no, but unrelated.
iPhone X (iOS 11) Safari - ok
iPhone X (iOS 11) Chrome - no, but unrelated.
iPhone 7 (iOS 10) Safari - failed, because of old versions not our problem

We can't figure out why from our own devices, 2 out of 3 do not stream audio.
We disconnected everything from them, turned off bluetooth devices, watches, airpods, etc. the browser's clearly ask for permissions to use video and mic, and we provide, yet we only playback Video and no audio at all.

**Comment by mustafaboleken** [comment]
After the investigation steps, these are the related issues.

https://github.com/ant-media/Ant-Media-Server/issues/4628
https://github.com/ant-media/Ant-Media-Server/issues/4662

**Comment by mekya** [comment]
Hi @findgr ,

In my test last week, I could reproduce the problem on iPhone 7 iOS 15.7.1 Safari. But I've just tested this scenario again, it's working for me at this time. Video and Audio OK. 

Do you still have the same problem? If yes, shall we get connected to reproduce together?

Regards,
Oguz

**Comment by findgr** [comment]
@mekya 

yes running all the test cases seems to be working now

**Comment by mekya** [comment]
Thank you for the update @findgr 

Let me know if I can do anything for you.
