### ISSUE TITLE
Alerts for server crashes, CPU overload, etc.

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#4739]
**Is your feature request related to a problem? Please describe.**

Can we have a functionality that, when something significantly affects the AMS webapps (like : CPU Overuse, Crash, etc). In order to minimize the losses and quickly address problems at our end, the administrator should receive an email or notification through any way.

**Comment by rahul78275** [comment]
Hello @yashtandon113 

Thanks for creating this issue, 
I had discussed this with selim few month back, but forgot to create an issue for this.

We can have notification setting feature in media console panel, As well I had proposed the idea of integration with some chat application like (skype, teams, telegram e.t.c). Sometimes mail goes in spam so user might not get the email.

I am writing this so that I would be notified if there is some update on this task.

**Comment by mekya** [comment]
What about creating some kind of webhook? After that we can integrate it to any service with some wrappers.
