### ISSUE TITLE
Can you change resolution in ant media?

### ISSUE THREAD

**Issue by D4RKPh0eNiX2** [ant-media/Ant-Media-Server#4820]
#4539 

### Short description
I'm fairly new to ant media I have both community and enterprise, I tested my 4k and HD video stream on YouTube on both community and enterprise through the live app on ant media but the output quality is still at 360p, is there a way to change it, so that my output quality is higher? because I want to be able to stream in 4k.

### Environment

* Operating system and version: Windows 10 latest
* Java version: latest
* Ant Media Server version: community and enterprise latest
* Browser name and version: chrome latest

### Expected behavior
Output of video to YouTube should be either 1080p or 2160p

### Actual behavior
Output is only coming out at 360p with adaptive streaming set

**Comment by yashtandon113** [comment]
Ongoing discussion on https://community.antmedia.io/topic/1621-can-you-change-resolution-in-ant-media

**Comment by yashtandon113** [comment]
@D4RKPh0eNiX2 

1. **Update:** H264 encoded 4K video works well using AMS when republishing to YouTube. To watch a 4K stream on YouTube, we must select the latency option as Normal latency on YouTube side. Following that, you'll see the 1440p and 4K options, as shown below:

![Screenshot (56)](https://user-images.githubusercontent.com/82374739/226200969-e877cf33-239c-44c7-97f0-53401c0ff6fb.png)

Below are the parameters of 4K video that I used in a playlist.

```
Duration: 00:00:26.83, start: 0.000000, bitrate: 72186 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 3840x2160, 71923 kb/s, 59.98 fps, 60 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2023-03-19T13:56:50.000000Z
      handler_name    : VideoHandle
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s (default)
```

The recommended upload encoding settings for YouTube videos can be found at [this link](https://support.google.com/youtube/answer/1722171?hl=en#zippy=).

If your 4K video is H265 encoded, I recommend converting it to H264 on your end with an encoder such as OBS, FFMPEG, or Handbrake software. Please ensure that your local system is powerful enough to transcode 4K H265 video to 4K H264 video.

2. **For Developers:**

On server side, 4K H265 video was transcoding to H264 but stream did not publish to YouTube while when I used 1080p H265 video, the streams was published to YouTube successfully.

**AMS version:** 2.5.3
**Server specifications:** 16 core CPU server

**Reproduce scenario:**
1. Upload any 4K H265 encoded mp4 video on server
2. Create a playlist
3. Add any one ABR (1080p for example) to transcode it with H264
4. Add YouTube RTMP end point
5. Start Playlist

**Expected behavior:**
Stream should published on YouTube.

**Actual behavior:**
Stream did not publish on YouTube while it was fine on the server.

Below are the logs when used 4K video with H265 video.

[4k-H265.txt](https://github.com/ant-media/Ant-Media-Server/files/11012206/4k-H265.txt)

**Comment by yashtandon113** [comment]
I am closing this issue.

A separate Git Hub issue has been created for the second issue: - Check https://github.com/ant-media/Ant-Media-Server/issues/4932
