### ISSUE TITLE
VoD Streaming Folder setting working strange

### ISSUE THREAD

**Issue by Tolarion** [ant-media/Ant-Media-Server#4842]
### Short description
I'm trying to set the folder to upload VODs. Files is uploading to default path.

### Environment

* Operating system and version: Ubuntu 20.04 LTS on Arm64
* Java version: got ava.lang.Error: Properties init: Could not determine current working directory on clean machine after AMS Install
* Ant Media Server version: Community Edition 2.6.0-SNAPSHOT 20230221_1439
* Browser name and version: Yandex Browser 23.1.2.987 (64-bit)

### Steps to reproduce
1. Go to Application - LiveApp - Setting  and set VoD Streaming Folder to: /data/ant_storage
2. In /usr/local/antmedia/webapps/LiveApp/streams the symlink to /data/ant_storage is automatically created
3. Uploading some mp4 file to LiveApp VoD

### Expected behavior
file appears in /data/ant_storage

### Actual behavior
file appears in /usr/local/antmedia/webapps/LiveApp/streams

 

### Logs
[ConsoleLog](https://pastebin.com/9UAdJJ8e)
[ErrorLog](https://pastebin.com/Gc4a9NyP)

**Comment by yashtandon113** [comment]
@Tolarion 
Thank you for reporting your problem here.

**VoD streaming Folder** feature is to link your recordings (mp4 files) from another directory to AMS. You can find more information [here](https://resources.antmedia.io/docs/recording-live-streams?highlight=recor#link-recordings-of-another-folder-to-ams).

To record your streams to another directory, you must first create a symbolic link. Please see [this document](https://resources.antmedia.io/docs/recording-live-streams?highlight=recor#storing-recordings-to-another-directory) for more information.

There was an issue with symbolic links in v2.5.3, as stated on [this Git Hub issue](https://github.com/ant-media/Ant-Media-Server/issues/4748), but it is now fixed. As a result, you can get the most recent community version snapshot from [here](https://oss.sonatype.org/service/local/repositories/snapshots/content/io/antmedia/ant-media-server/2.6.0-SNAPSHOT/ant-media-server-2.6.0-20230225.130052-162-community.zip).

Please feel free to ask if you have any questions.

**Comment by timantmedia** [comment]
The documentation page has changed. It's now located here https://antmedia.io/docs/guides/recording-live-streams/
