### ISSUE TITLE
The Onvif Url doesn't changed

### ISSUE THREAD

**Issue by babutree** [ant-media/Ant-Media-Server#4859]
### Short description
when I change and submit onvif URL, the URL doesn't changed
![image](https://user-images.githubusercontent.com/21240045/222655904-dd4cbee7-10c3-4f8a-a6f2-92bb4ae015d0.png)

### Environment

Docker nibrev/ant-media-server:latest

### Steps to reproduce
1. Edit Stream
2. Change Onvif URL: rtsp://admin:12345678@192.168.1.198:554/stream**2** and Save
3. But it's always rtsp://admin:12345678@192.168.1.198:554/stream**1**

**Comment by mustafaboleken** [comment]
Hi @babutree 
Thank you very much for reposting this error. I put it into backlog. We will schedule it in the next sprint.

**Comment by mekya** [comment]
Hi Guys,
Just for your information, RTSP URL(rtsp://admin:12345678@192.168.1.198:554/stream1) is not an ONVIF URL.

ONVIF URL is a http endpoint that server communicates for controlling the IP Camera.
RTSP URL is a streaming URL that server gets the video/audio stream from that URL

So this is an expected behaviour.

@babutree 
If you want to use RTSP URL directly, you can add it as a `Stream Source` in the web panel with RTSP URL. I'm attaching the screenshot for your convenience.
 
<img width="1717" alt="Screenshot 2023-06-22 at 17 15 40" src="https://github.com/ant-media/Ant-Media-Server/assets/3456251/1846ac30-2c55-4c5d-bdc9-22e4116396bf">

Guys,
So I'm closing this issue and please feel free to re-open if it does not work for you.
