### ISSUE TITLE
webhook at the p2p communication

### ISSUE THREAD

**Issue by SangukChoi** [ant-media/Ant-Media-Server#4891]
### Short description
I don't know this is bug or not.
We setted the webhook URL at the manage page of ant media server.
When we use conference.html sample, we receive event successfully(liveStreamStarted / liveStreamEnded...)
However when we use peer.html sample, we receive nothing.

Isn't webhook supported at the p2p communication?

**Comment by yashtandon113** [comment]
@SangukChoi
Thanks for your question.
Yes, there is no webhook for p2p communication.

It is an expected behavior because, in p2p mode, Ant Media Server only functions as a signalling server, which is used to exchange ice candidates between one peer and another. Please see the following blog post for more information.
https://antmedia.io/what-is-webrtc-and-how-webrtc-works/

**Comment by SangukChoi** [comment]
@yashtandon113 

Thank you for the explanation. I understood well.
Have a good day :)
