### ISSUE TITLE
Installation "cannot stat 'ant-media-server': No such file or directory"

### ISSUE THREAD

**Issue by jhelmholz** [ant-media/Ant-Media-Server#4902]
### Short description

Installing Ant-Media-Server on Ubuntu 20.04 Desktop fails with the message "cannot stat 'ant-media-server': No such file or directory".
Also attempted to install on 18.04, but got the same error.

### Environment

* Operating system and version: Ubuntu 20.04 
* Java version: 11.0.18
* Ant Media Server version: 2.5.3
* Browser name and version:

### Steps to reproduce

1. set dir to folder where .zip is located
2. download the installation script
3. run the installation script

### Expected behavior
Installation succeeds,  command sudo service antmedia status should return a value other than "Unit antmedia.service could not be found."

### Actual behavior
Able to fetch installation script, but running the installation script returns error "cannot stat 'ant-media-server': No such file or directory"

### Logs
https://pastebin.com/hGZPvwLK

**Comment by yashtandon113** [comment]
@jhelmholz 
It appears that you are attempting to install using the source code file rather than the actual software zip file. If you want to install the community edition v2.5.3, download it from [here](https://github.com/ant-media/Ant-Media-Server/releases/download/ams-v2.5.3/ant-media-server-community-2.5.3.zip).

All zip files for community editions are available at https://github.com/ant-media/Ant-Media-Server/releases.

If you want to use Enterprise edition, a free trial of the EE is available at https://antmedia.io/free-trial/.

**Comment by mekya** [comment]
Thank you @yashtandon113 for the answer and thank you @jhelmholz for the question. 

I'm closing this issue. Please feel free to open if it's not working for you @jhelmholz
