### ISSUE TITLE
Remote Desktop Workspace & Collaboration

### ISSUE THREAD

**Issue by umtcylmz** [ant-media/Ant-Media-Server#4928]
More than one user can connect to Remote Computers via their web browsers and control the remote desktop with their mouse and send keyboard events to the Remote Computer. 

### Features & Requirements
- Ultra Low Latency (WebRTC) technology is being used in controlling the Remote Desktop. Typical latency is between 200-400ms  
- Users can connect to remote Desktop with Chrome. 
- Users mouse and keyboard events are sent to the Remote Computer to control it

### Typical Scenario
- Remote Desktop App joins the Ant Media Server and does not send any video/audio at first because no user is connected
- User joins the Remote Desktop and Remote Desktop App starts to send the screen capture. User will see the screen capture of the remote computer instantly. 
- User can control the Remote Desktop through mouse and keyboard events.

Also, after the development is done, instructions and/or documentation about how to implement will be necessary.

**Comment by mekya** [comment]
PoC is available here https://github.com/ant-media/TunaDesk

Known issues and Future Developments
- [ ] Some keyboard events are not working for me such as `backspace`. I'm not sure it may be an expected behaviour 
- [ ] keyup`, `keydown`, `double-click` events should be implemented
- [ ] `enter` event stops the player on the client and I did need to quick the play button of the player again. As a quick workaround solution, [`play` method is called](https://github.com/ant-media/TunaDesk/blob/master/src/main/webapp/remote_desktop.html#L283). 
- [ ] We need to find an easy way to run the host application(nodejs). Electron or pm2 may be a solution.  In the production level, the user should not run any command in the terminal. Everything should be handled with a couple of clicks.  
- [ ] The requirement above should be implemented
  >Remote Desktop App joins the Ant Media Server and does not send any video/audio at first because no user is connected
- [ ] Running the Chrome browser with the headless mode in nodejs may be a good solution to make life easy for the host applications. 
- [ ] Websocket connection between host webapp and host nodejs app can be reconnected automatically if nodejs app restarted during the session.

**Comment by mekya** [comment]
- Scroll up and scroll down
- Window dragging 
- UI according to brand guide
- Enter button
- Make setting under sub-window
