### ISSUE TITLE
can i use rtsp for puplish audio only 

### ISSUE THREAD

**Issue by m0dawood** [ant-media/Ant-Media-Server#494]
# Issue
Im tring to puplish audio only stream using rtsp 
the liberary i use notify me that the connection success to the server 
but when log into console i got nothing

### Steps to reproduce

RtspOnlyAudio audio = new RtspOnlyAudio(new ConnectCheckerRtsp() {
      @Override
      public void onConnectionSuccessRtsp() {
        Log.v("connected", "sucess");
      }

      @Override
      public void onConnectionFailedRtsp(String err) {
        Log.v("connected", "failed: "+err);
      }

      @Override
      public void onDisconnectRtsp() {
        Log.v("connected", "failed: disc");
      }

      @Override
      public void onAuthErrorRtsp() {
        Log.v("connected", "failed: auth");
      }

      @Override
      public void onAuthSuccessRtsp() {
        Log.v("connected", "auth");
      }

    });
    audio.setProtocol(Protocol.UDP);
    audio.prepareAudio();
    audio.startStream("rtsp://<server>/LiveApp/stream1");

**Comment by mekya** [comment]
Hi @m0dawood ,

Thank you for asking. Sorry for late reply. 

Technically yes you can. On the other hand,   RTSP usage is getting down globally so that we do not RTSP plans for future for now. We generally plans for WebRTC and support RTMP for legacy issues. So that I recommend you to use RTMP if possible. 

Another option is using WebRTC. I think we can provide Android WebRTC SDK for you to try. You can publish only audio on android with that.   

Regards,
A. Oguz

**Comment by m0dawood** [comment]
ok i used webrtc and send audio only but when playing the stream many devices did not work 
some of them worked thats becuase im getting video  in the sdp offer  
i cant use your sdk as my app build with react-native so i have to do it using RN webrtc module 
[https://github.com/oney/react-native-webrtc](url)

im not advanced in webrtc so can you help me with that and thanks for your response

**Comment by SelimEmre** [comment]
Hi @m0dawood,
Thank you for your interest. Do you still have problems? If the problem persists, can you re-open this issue?
