### ISSUE TITLE
work with playlist

### ISSUE THREAD

**Issue by studentAlanMorgan** [ant-media/Ant-Media-Server#5026]
Hello, explain to a noob how to add a lot of videos to a playlist?
I have more than 200 videos and they need to be placed in a playlist, the documentation describes how to add via a link, but adding a large number of videos one at a time is a long time. in rest api is also only an option with the addition of one video. Is there any other way how to implement this somehow through the configuration files?

**Comment by yashtandon113** [comment]
Related community post: https://community.antmedia.io/topic/1706-playlist-work/#comment-6441

@studentAlanMorgan 
You are correct, and I appreciate your feedback on bulk uploading. We'll try to implement it asap. I have created the Feature request as well https://github.com/ant-media/Ant-Media-Server/issues/5079.

In the meanwhile, you can copy your files from your PC to the server using a command-line (scp) tool or any UI application like WinSCP rather than uploading them one at a time.

You can utilize that folder as a VOD folder in the application settings after the files have been uploaded. For the Web Panel to link to another directory holding MP4 files as a VoD directory:

- Login to Ant Media Server panel
- Go to Applications (LiveApp/WebRTCAppEE) settings
- Set VoD streaming folder (i.e., add directory where MP4 files are located).

There is also Rest API to import VOD files from different folder. Check https://antmedia.io/rest/#/VoD%20Rest%20Service/importVoDs

In previous version there was an issue with this Rest API which is fixed by the developer following the below GitHub issue.
https://github.com/ant-media/Ant-Media-Server/issues/4866

It will be merged in the next release.

I hope it helps.

**Comment by yashtandon113** [comment]
@studentAlanMorgan 
One of my colleagues also shared one more work around solution on https://github.com/ant-media/Ant-Media-Server/issues/5079

So I am closing this issue for now. Please feel free to reopen the issue if you have any further questions.
