### ISSUE TITLE
YouTube RTMP streaming not working with video only VOD file (NO AUDIO)

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5183]
### Short description
when adding a video only VOD  file as a playlist src, then YouTube live streaming is not working

### Environment

* Operating system and version: Ubuntu 22.04
* Java version: 
* Ant Media Server version: 2.6.0
* Browser name and version: chrome

### Steps to reproduce
1. upload a video only VOD file
2. create a playlist and add the VOD file as a src
3. add YouTube RTMP link for streaming to YouTube.
4.Start Broadcast 

### Expected behavior
YouTube streaming should work and  video should show up on youtube

### Actual behavior
Video not showing up on YouTube.

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links [here__](https://pastebin.com/PBQWV29w)

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by drankiebeverly** [comment]
I am a little confused on the matter. Because the video uploaded does have audio. But upon checking the live stream I don’t actually see the video playing but I can hear the audio. But when I preview the video on the VOD upload section both video and audio are working fine. 

[66.228.60.240:5080/LiveApp/play.html?name=d0VjN3qKCXio1685416741474](http://66.228.60.240:5080/LiveApp/play.html?name=d0VjN3qKCXio1685416741474)

**Comment by mekya** [comment]
Hi @USAMAWIZARD,
I think this problem is about youtube policy. It does not accept video-only live streams. This is not something we can fix directly. 

The user has some options to do that by using the filter plugin or [adding dummy audio](https://stackoverflow.com/questions/12368151/adding-silent-audio-in-ffmpeg) to the file and streaming.

@drankiebeverly,
I think your problem's different. Could you please your video or at least 2-3 minutes of your video to test it on our end to reproduce the problem?

**Comment by mekya** [comment]
I'm closing this issue for the inactivity. Please feel free to re-open if you still have this issue
