### ISSUE TITLE
Unable to connect to websocket

### ISSUE THREAD

**Issue by Samriddha01** [ant-media/Ant-Media-Server#5376]
After successfully building and running the source code... while trying to connect with the Antmedia server, getting the below mentioned error...
> _websocket_adaptor.js:46 WebSocket connection to'wss://localhost:5443/WebRTCApp/websocketrtmpForward=undefined&target=origin'failed:_

**Comment by mekya** [comment]
Hi @Samriddha01 

You're trying to connect to 5443 with wss. I think you may not have SSL installed on your local computer.
Please try with 5080 and ws. I mean connect this address and pay attention that there should be **question mark** between `websocket` and `rtmpForward`

```
ws://localhost:5080/WebRTCApp/websocket?rtmpForward=undefined&target=origin
```

**Comment by Samriddha01** [comment]
Still getting the error...

`websocket_adaptor.js:46  WebSocket connection to 'wss://pradnya11.pune.cdac.in:5443/WebRTCApp/websocket?rtmpForward=undefined&target=origin' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID`


Also, the certificate is self signed and we have to run it on 5443 as it is in the requirement.

**Comment by mekya** [comment]
Hi @Samriddha01,

It's better to use the recommended way. Just pay attention the response.

```
ws://localhost:5080/WebRTCApp/websocket?rtmpForward=undefined&target=origin
```

It's `ws` and `5080`. In your sample, you're using `wss` and `5443`. 

I mean there is no SSL certificate on your localhost. This is why wss and 5443 does not work for you. 

Please make it work first (use the samples)  and then change the parameters as you wish. This way you can save time on both ends. 

I'm closing this issue because it's a configuration issue.

If you need support, you can ask your questions on [Discussions](https://github.com/orgs/ant-media/discussions)

Cheers
Oguz
