### ISSUE TITLE
[Flutter SDK] Cannot install sample project.

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5420]
Whenever we try to install sample project, it throws `Method 48288(Lorg/webrtc/PeerConnectionFactory;.-$$Nest$smnativeCreatePeerConnectionFactory) has code, but is marked native or abstract`

![Screenshot 2023-07-31 at 12 03 31](https://github.com/ant-media/Ant-Media-Server/assets/23143596/4ddaae11-39cb-4e3e-bc86-2370c69ef33f)

**Comment by USAMAWIZARD** [comment]
It is occurring because of upgrading the webrtc_flutter library
I have tried various things as mentioned in different discussion forms  like upgrading gradle version
setting mulitdex configuration in the application gradle file but nothing seems to work will do some more investigation
 about the issue.

**Comment by mustafaboleken** [comment]
I solved the problem by updating all native codes. You can check https://github.com/ant-media/WebRTC-Flutter-SDK/pull/27

**Comment by USAMAWIZARD** [comment]
Thank you very much for your help @mustafaboleken
