### ISSUE TITLE
Add stream api not working when dynamically  adding stream to conference. 

### ISSUE THREAD

**Issue by USAMAWIZARD** [ant-media/Ant-Media-Server#5510]
### Short description
stream not adding into conference when calling this api
https://antmedia.io/rest/#/BroadcastRestService/addStreamToTheRoom

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version: 2.6.2
* Browser name and version:

### Steps to reproduce
1. stream a video from obs to conference application
2. call https://antmedia.io/rest/#/BroadcastRestService/addStreamToTheRoom
3. stream will not be added

### Expected behavior
stream should be added conference 

### Actual behavior
stream is not added even the response is 200
 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by lastpeony** [comment]
This issue arises in multi-track conferences due to a limitation in the API call used to add a stream to a conference. This call does not add the stream to the subtracks of the conference room's stream. Fortunately, a fix has been developed, and a pull request (PR) will be submitted shortly to address this issue.

**Comment by USAMAWIZARD** [comment]
Thanks for the update @lastpeony
