### ISSUE TITLE
Investigate the lower fps issue

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#5583]

**Comment by mekya** [comment]
@burak-58 will provide instructions how to resolve about this issue

**Comment by burak-58** [comment]
Among AMS users, one of the most used scenario is RTMP to WebRTC.
WebRTC is a real-time streaming protocol and it doesn't like B-frames. If RTMP has B-frames and you play it with WebRTC, there are some problems at the player.

**If there is no ABR**: then the problem is obvious. You will see only pictures (of key frames), not a continuous video.
**If there is ABR:** You can see a video. But B-frames are decoded but some of them are dropped by the server. So we can play the video but with lower fps. This affects the stream quality and smoothness. It causes mini jumps on the video.

As a result, regardless of ABR enabled or disabled, we should tell users that they should publish RTMP streams without B-frames.
