### ISSUE TITLE
Support for CUDA 12

### ISSUE THREAD

**Issue by SimJeg** [ant-media/Ant-Media-Server#5592]
Hello,

 Are there any plans on releasing a version compatible with CUDA 12 in the upcoming future?

Thanks,
Simon

**Comment by midgard-as** [comment]
I'd be interested in that version as well !

**Comment by mekya** [comment]
Thank you for creating this issue @SimJeg @midgard-as 

Yes, definitely we'll update the CUDA and FFmpeg probably at the same time. In order to give correct priority for this issue, could you please reach out to contact@antmedia.io?

To be transparent, we schedule and set priority to the issues according to the craters below 
- If the issue is general and/or important 
- If the issue is coming from a current enterprise user and the usage of the user
- If the issue is coming from a prospective enterprise user 

If the issue does not fit any of the criteria above, we're still doing our best to schedule according to the urgency of the users. 

Please also let me know if you recommend anything about scheduling the issues. 
I'm on the side to have transparent, clear and win-win for everyone.

Cheers

**Comment by dsjohnston** [comment]
any scheduling or prioritisation update?

**Comment by burak-58** [comment]
We have recently update the Cuda version to 12.6. You can download the latest Snapshot release from antmedia.io after login. We will update the related documents soon.

**Comment by mekya** [comment]
Hi @SimJeg 
It's done through this issue 
https://github.com/ant-media/Ant-Media-Server/issues/6551

The version is CUDA 12.6. 

Let me know if I can help for anything

FYI
