### ISSUE TITLE
Video recording problem if set width and height in media constraints

### ISSUE THREAD

**Issue by e-vural** [ant-media/Ant-Media-Server#5631]
https://github.com/ant-media/Ant-Media-Server/assets/11753784/1e22f17e-afc3-4ede-9c9d-679cbe9f0b3e

(Open that video google chrome new tab you will see problem)

If set width and height params that problem occurs . 

```

"video": {
            "facingMode": "environment",//environment
            "width": {
                "exact": 1280,
            },
            "height": {
                "exact": 720
            },

        }
```

Resolution started from 320x180. Every 4 seconds resolution changes and video getting bigger.  Because of that ,iphone and mac devices can not play that video after 4 seconds in native players.

**Comment by mustafaboleken** [comment]
This problem came from the nature of WebRTC but as a workaround solution you can define [a custom script ](https://antmedia.io/docs/guides/recording-live-streams/user-defined-scripts/) which will be triggered as soon as MP4 mixing finished. You can run `ffmpeg -i stream1.mp4 -profile:v baseline -level 3.0 -acodec aac output.mp4` script to reorganise the recorded file.

**Comment by mustafaboleken** [comment]
Other than the solution that I provided, e-vural opened [a pull request](https://github.com/ant-media/Plugins/pull/82) with a different solution. I'm closing this issue right now.
