### ISSUE TITLE
GPU Memory leak - some amount of memory is not freed after stream finish

### ISSUE THREAD

**Issue by burak-58** [ant-media/Ant-Media-Server#5632]

**Comment by congkuan** [comment]
hi,May I ask if this problem has been fixed.

**Comment by slodhi786** [comment]
Happening same thing here as well. I created an EC2 instance with a GPU and installed the latest version of Ant Media Server. However, I am still experiencing crashes during live streaming. Upon investigation, I discovered that Ant Media Server is not releasing the Nvidia GPU after the publishing process is complete. As a result, when new streams start, it throws an out of memory exception. This could be the main reason for the issue, as it was not occurring in earlier releases. See images below

**During Publish**
![image](https://github.com/ant-media/Ant-Media-Server/assets/71716355/1cf2b994-aa16-4d1e-bb84-8201763a26bd)


**After Publish**
![image](https://github.com/ant-media/Ant-Media-Server/assets/71716355/7b071623-a14e-4b4a-a891-6a1e1dc6cfed)


**Expected behavior after publish** 
![image](https://github.com/ant-media/Ant-Media-Server/assets/71716355/6f38467c-5466-4656-895f-5c20772e9d75)

**Comment by slodhi786** [comment]
I discovered that it is not only about GPU memory. same thing also happening with system memory.

**Comment by lastpeony** [comment]
I have also replicated this problem. It seems that there are no issues with RTMP, but the problem only arises when using WebRTC. Specifically, memory is not released when the publishing process is stopped.
