### ISSUE TITLE
iOS SDK Disconnection Issue

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5808]
When we end a conference meeting or stop publishing and start it again, we face data channel and audio issues and there are some unclosed classes.

Reproduced scenario:

- Join in a conference room with JS SDK (Participant A)
- Join in a conference room with iOS SDK (Participant B)
- Participant B leaved from the room
- Participant B joins the same room again
- Audio of Participant B is not received by participant A

It's reported by OnRemote AG

For more information: https://antmedia.freshdesk.com/a/tickets/109238

**Comment by mustafaboleken** [comment]
Here are the findings that the user observed:

When the publish started, following processes are active:

<img width="344" alt="ZVwEw3zS5zK6GEoMGKpmBXrVCbMPGzOykw" src="https://github.com/ant-media/Ant-Media-Server/assets/23143596/d314be04-dd9f-4516-b978-69da6364c280">

When the publish stopped, following processes are remained:

<img width="246" alt="QIbOtG1u6Jf71wU6PIKYXh8t0cGgfGJtXA" src="https://github.com/ant-media/Ant-Media-Server/assets/23143596/fade7013-d3b9-4a7d-8b63-7317b4578609">

When we leave from the conference room, following processes are remained:

<img width="233" alt="lNh_fXw3GvQqaQu2jI7d70iQH7uQD9Plpw" src="https://github.com/ant-media/Ant-Media-Server/assets/23143596/a1ae885f-fdfb-4a3a-b5ec-2868f662ede4">

**Comment by mekya** [comment]
Hi @mustafaboleken,

I've checked this scenario with both cases. Let me tell what I have done.

Environment:  
iOS App is the master version here -> https://github.com/ant-media/WebRTC-iOS-SDK/
Ant Media Server is the 2.8.0-SNAPSHOT running on ovh36.antmedia.io

Steps
1. I've connected to ovh36's multitrack-conference.html from Chrome web browser (JS SDK -> Participant A)
2. I've opened the Conference Sample iOS App and enter the same room (iOS SDK -> Participant B)
3. Participant A(JS SDK) hears the Participant B in iOS App
4. I made Participant B(iOS SDK) leave the room 
5. I made Participant B(iOS SDK) re-join the room again
6.  I check Participant A(JS SDK hears the Participant B(iOS App)

I mean everything as expected and I don't encounter the problem here. 

Secondly, I've changed the order of the Participant A and Participant B. The problem does not happen again. 

Please let me know what the differences are between the scenario above and your scenario that creates the problem

**Comment by mustafaboleken** [comment]
Hi @e-vural

Can you please check the latest comment?

**Comment by mekya** [comment]
Hi @mustafaboleken, @e-vural

I've keep testing the scenario again. Fortunately, I see this problem in some cases. On the other hand, I don't have a clear reproduce scenario. I'm investigating and try to locate the problem. 

If you have clear reproduce scenario that you encounter this problem every time, please let me know. It may help me fix the problem faster. 


Anyway, I keep working on this issue and I'll update you.  

Regards
Oguz

**Comment by mekya** [comment]
Hi @mustafaboleken , @e-vural,

I've reproduced the problem on my end with the scenario below. The difference is that the Step 3-4 are for Participant A. 

```
1. Join in a conference room with JS SDK (Participant A)
2. Join in a conference room with iOS SDK (Participant B)
3. Participant A left from the room
4. Participant A joins the same room again
5. Audio of Participant B is not received by participant A
```

Figuring out the root cause of the problem took some time. The problem is not about iOS SDK, it's about server side. I mean it behaves differently when one client is connecting from iOS. I've fixed and it's working for me. We can send a snapshot and you can test it on your end to check if it's working for you.  

Have a great weekend

Cheers
Oguz

**Comment by e-vural** [comment]
Hi @mustafaboleken , @mekya .

I will test again and try to detailed explain problem at Monday.

**Comment by e-vural** [comment]
> Hi @mustafaboleken , @e-vural,
> 
> I've reproduced the problem on my end with the scenario below. The difference is that the Step 3-4 are for Participant A.
> 
> ```
> 1. Join in a conference room with JS SDK (Participant A)
> 2. Join in a conference room with iOS SDK (Participant B)
> 3. Participant A left from the room
> 4. Participant A joins the same room again
> 5. Audio of Participant B is not received by participant A
> ```
> 
> Figuring out the root cause of the problem took some time. The problem is not about iOS SDK, it's about server side. I mean it behaves differently when one client is connecting from iOS. I've fixed and it's working for me. We can send a snapshot and you can test it on your end to check if it's working for you.
> 
> Have a great weekend
> 
> Cheers Oguz

Hi @mustafaboleken , @mekya .

Do you  still need more information? I can detailed explain the problem at Monday. 
Also if you send new snapshot, we can test that problem.

**Comment by mekya** [comment]
Hi @e-vural,
Thank you. I don't need more information. 

Let me merge the PRs and send you a snapshot to check if it works for you

Regards
