### ISSUE TITLE
Camera switch issues and black screen

### ISSUE THREAD

**Issue by swatisinha-mis** [ant-media/Ant-Media-Server#5816]
We are facing some issues related to the camera device list when we try to get it. The problem is that when we try to get the video source list it sometimes gives us half the device (Web Chrome, Android Chrome and on iPhone Safari and Chrome) or sometimes empty data in the object (on iPhone Safari and Chrome) returns. We are also facing camera switch issues during live demo that is when I do not select camera from camera list it automatically opens back camera for streaming or when I select any camera option it opens back camera by default in Android but it shows up black Screen in iOS and sometimes even in Android devices(specially samsung and motorola) but streaming is publishing in background with audio but sometime video got stuck & sometime its publishing with back camera on.

I am using following version mentioned below:

Operating system and version: Ubuntu 20.04.6 LTS,
Angular : version 14.2.0,
Ant-Media-SDK version: "@antmedia/webrtc_adaptor": "^2.7.0-SNAPSHOT-2023-Oct-21-01-09",
Ant Media Server version: Enterprise Edition 2.6.4 20230827_1351,
ngx-webcam : ^0.4.1

How to resolve this? Please help us.

**Comment by yogeshJain0727** [comment]
@lastpeony @mustafaboleken @timantmedia Please help us resolve this issue.

**Comment by mekya** [comment]
Hi @swatisinha-mis and @yogeshJain0727,

Thank you for raising the issue. We definitely would like to help you. On the other hand, it seems that you reported issue in free text format and it requires us to analyze it carefully and I also see that you report several issues above.  

What about proceeding one by one. Let us know what is the first thing to proceed with simple bug report template below so that we reproduce the problem.  If you report this way, we put this to the backlog to schedule and help you resolve the issue.
```
Steps to reproduce
1.
2.
3.

Expected behavior:
...

Actual behavior:
... 
```

Full bug report template is also [available in creating issue](https://github.com/ant-media/Ant-Media-Server/issues/new/choose)

**Comment by yogeshJain0727** [comment]
### Short description
__Brief description of what happened__

We are facing problem when we start publishing live streams using the front camera it shows up black Screen in Android devices(especially Samsung & Motorola and vivo) in any browser but streaming is publishing in the background with audio and camera on. Or when we start publishing live stream using back camera the video gets stuck & sometimes it gets published with back camera. In both scenarios camera switch functionality is not working at all, this causes the live video stream to freeze.


### Environment

* Operating system and version: Ubuntu 20.04.6 LTS
* Java version: version 14.2.0
* Ant-Media-SDK version: "@antmedia/webrtc_adaptor": "^2.7.0-SNAPSHOT-2023-Oct-21-01-09",
* Ant Media Server version: Enterprise Edition 2.5.3 20230107_0851, Enterprise Edition 2.6.4 20230827_1351
* Browser name and version: Chrome, Firefox, Safari
* ngx-webcam : ^0.4.1


### Steps to reproduce
1. Use the Ant Media SDK to create a stream.
2. Then, display a list of camera devices. When we select the front camera, it shows the back camera and on certain devices (Samsung, Motorola, and Vivo), it displays a black screen. Additionally, when we switch cameras during an ongoing streaming session, the stream freezes or becomes stuck.


### Expected behavior
__Put as much detail here as possible__
After starting the stream, the switch functionality works properly and no black screen is shown to the publisher.

### Actual behavior
__Put as much detail here as possible__
After starting the stream, the switch functionality is not working properly. For some specific devices (Samsung, Motorola, and Vivo), a black screen is shown to the publisher.

**Comment by mekya** [comment]
hi @yogeshJain0727,

Thank you. You're great. I've put it to the backlog with high priority. I think It will be scheduled soon. 

Cheers
Oguz

**Comment by USAMAWIZARD** [comment]
@yogeshJain0727 @swatisinha-mis  Please correct me if I am wrong.
Please correct me if I am wrong
1. publish a stream
2. select the front camera,
3. it will show the back camera ( not reproducible )
4. and on certain devices (Samsung, Motorola, and Vivo), it displays a black screen.
5. Additionally, when we switch cameras during an ongoing streaming session, the stream freezes or becomes stuck.

I have tried reproducing the problem on Motorola g32 using our sample example page by publishing stream but the issue is not reproducible device selection is working as expected

**Comment by swatisinha-mis** [comment]
@USAMAWIZARD Yes, Exactly we are facing this problem in our angular project. Detailed information is mentioned above.

**Comment by swatisinha-mis** [comment]
@USAMAWIZARD 
1. select the front camera first,
2. publish a stream
3. it will show the back camera to the publisher but streaming with front
4. and on certain devices (Samsung, Motorola, and Vivo), it displays a black screen to the publisher.
5. Additionally, when we switch cameras during an ongoing streaming session, the stream freezes or becomes stuck on certain devices (Samsung, Motorola, and Vivo).

**Comment by USAMAWIZARD** [comment]
@swatisinha-mis I tried but I cannot reproduce the issue with our sample , can you try to reproduce the issue with our sample example https://antmedia.io/webrtc-samples/webrtc-publish-webrtc-play/

**Comment by swatisinha-mis** [comment]
@USAMAWIZARD yes we can, but when we intigrate the same function in our angular code is not working properly. Only differance is in sample you use webrtc js file and i'm using npm library of antmedia.

**Comment by USAMAWIZARD** [comment]
@swatisinha-mis which version of @antmedia/webrtc_adaptor are you using ?

**Comment by swatisinha-mis** [comment]
**Environment**

Operating system and version: Ubuntu 20.04.6 LTS
Java version: version 14.2.0
Ant-Media-SDK version: "@antmedia/webrtc_adaptor": "^2.7.0-SNAPSHOT-2023-Oct-21-01-09",
Ant Media Server version: Enterprise Edition 2.5.3 20230107_0851, Enterprise Edition 2.6.4 20230827_1351
Browser name and version: Chrome, Firefox, Safari
ngx-webcam : ^0.4.1

**Steps to reproduce**

Use the Ant Media SDK to create a stream.
Then, display a list of camera devices. When we select the front camera, it shows the back camera and on certain devices (Samsung, Motorola, and Vivo), it displays a black screen. Additionally, when we switch cameras during an ongoing streaming session, the stream freezes or becomes stuck.

**Expected behavior**

Put as much detail here as possible
After starting the stream, the switch functionality works properly and no black screen is shown to the publisher.

**Comment by USAMAWIZARD** [comment]
Two problems were reported in this issue. We had a meeting for this issue.

1. By default Back Camera is selected.
We found out the probem was not on the SDK level but on user's code level. switchVideoCameraCapture was never called when the different camera is sleeted in User' Code.

2.Camera switch not working on Motorola.  
Please update to this and it will fix the issue.
npm i @antmedia/webrtc_adaptor@2.8.0-SNAPSHOT-2023-Nov-27-08-06

**Comment by yogeshJain0727** [comment]
Thanks, @USAMAWIZARD for your support

**Comment by USAMAWIZARD** [comment]
You'er Welcome @yogeshJain0727
