### ISSUE TITLE
IP Filter for REST API does not work behind load balancer

### ISSUE THREAD

**Issue by yashtandon113** [ant-media/Ant-Media-Server#6044]
### Short description
If any specific IP is allowed in the IP filter for the Rest API, and if the server is running behind a load balancer, then it does not work. It works only if the 0.0.0.0/0 CIDR block is whitelisted.

### Environment
* Ant Media Server version: v2.7.0 and above

### Steps to reproduce
1. Deploy the server behind load balancer
2. Whitelist your IP in IP filter for Rest API
3. Call any Rest API

### Expected behavior
The Rest API call should work as expected

### Actual behavior
Rest API call does not work and IP not allowed error comes

**Comment by mekya** [comment]
Hi @yashtandon113,

Thank you for the issue. I think it's an expected behaviour for public IP addresses due to security reasons and let me provide you a solution. 

Firstly, let me tell why it's an expected behaviour in public IP addresses.

## Why it is a Problem?
- When we send a REST request to the load balancer, load balancer forwards the request in one of the backend server.
- Load Balancer forwards the request with `X-Forwarded-For` header by putting the original client IP address there as a value. 
- Ant Media Server uses [Remote IP Valve](https://tomcat.apache.org/tomcat-10.1-doc/config/valve.html#Remote_IP_Valve) which accepts the local network addresses as trusted. Check the `internalProxies` section in the link above. Otherwise, it causes a security vulnerability. 
- In this scenario, as far as I understand the problem is happening the load balancer and Ant Media Servers are not in the same private network and you encounter this problem. 

## Solution:
Fortunately, Remote IP Valve has options to change `internalProxies` and `trustedProxies`. 

>`trustedProxies`: Regular expression (using java.util.regex) that a proxy's IP address must match to be considered an trusted proxy. Trusted proxies that appear in the remoteIpHeader will be trusted and will appear in the proxiesHeader value. If not specified, no proxies will be trusted.

I'm using the `trustedProxies` for this case. Let me tell the story

1. I've created an instance having public IP address: 145.239.135.94. I've installed Nginx on it to forward the incoming request to ovh36 test server. In this scenario both Nginx instance and ovh36 test server have public addresses and they are in different regions.
2. I've open the `/usr/local/antmedia/conf/jee-container.xml` and find the line that includes `<bean id="valve.access" class="org.apache.catalina.valves.RemoteIpValve" />`.
3. I've changed the line as below and it looks like something below. Pay attention that I've added the load balancer address and trustedProxies
```xml 
<bean id="valve.access" class="org.apache.catalina.valves.RemoteIpValve" >
  <property name="trustedProxies" value="145.239.135.94"/>
</bean>
```

4. Restart the Ant Media Server
```
sudo service antmedia restart
```

5. I've then added my public address for REST IP Filter 

<img width="1733" alt="Screenshot 2024-02-02 at 11 23 07" src="https://github.com/ant-media/Ant-Media-Server/assets/3456251/430bf939-3792-4f37-b985-ceca06a9e184">

6. Then make a request to the load balancer with curl in my local terminal
```
curl http://145.239.135.94:5080/WebRTCAppEE/rest/v2/broadcasts/count 
```
7. Tadaaa 🎉 it returns the result.
```
{"number":1}
```

It's working for me in this scenario. Let me know if it works for you @yashtandon113 

Cheers
Oguz
