### ISSUE TITLE
Subscriber block does not work when playing the .m3u8 file with ABR enabled.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#6172]
### Short description
When ABR is enabled and playing the .m3u8 file directly, the subscriber block feature/API is not working.

### Environment
* Ant Media Server version: AMS v2.8.2

### Steps to reproduce
1. Enable Time-based One-time Password(TOTP) for Playing.
2. Enable adaptive streaming/transcoding.
3. Start a rtmp stream.
4. Generate the subscriber token for the streamId.
5. Play the .m3u8 file `ffplay -i "https://ams.antmedia.cloud:5443/LiveApp/streams/abcde_adaptive.m3u8?subscriberId=media&subscriberCode=337308"`
6. Call the subscriber block API `curl -X 'PUT' 'http://ams-14315.antmedia.cloud:5443/LiveApp/rest/v2/broadcasts/abcde/subscribers/media/block/30/play'
`

### Expected behavior
The playback should stop and the subscriber should be blocked.
### Actual behavior
The play continues and the subscriber is not blocked.

It works fine when playing with the embedded player, play.html

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by lastpeony** [comment]
I investigated this issue and it appears that when test_adaptive.m3u8 file is requested ffmpeg only passes query parameters on first m3u8 request and afterwards it does not request any more m3u8 and fetches .ts files without passing subscriberId and subscriberCode. Because of this behaviour blocking subscriber on air does not work.
As a workaround solution for ABR case spesific ABR m3u8(teststream_480p1000kbps.m3u8) file can be requested. On this case subscriber block on air will work just like no ABR case.
`ffplay -i "http://localhost:5080/WebRTCAppEE/streams/teststream_480p1000kbps.m3u8?subscriberId=lastpeony&subscriberCode=371505"
`

**Comment by Mohit-3196** [comment]
Thank you @lastpeony for your investigation and the workaround solution.
In case there are multiple Adaptive settings on the server then this solution is not likely to be affective as the users would like the bitrate to switch as per the internet connection.

**Comment by lastpeony** [comment]
We have a solution for this problem and its on PR.
If someone needs the fix urgently let me know.

**Comment by muratugureminoglu** [comment]
<div>Agent Mohit Dubey linked Freshdesk ticket <a href="https://antmedia.freshdesk.com/a/tickets/149903">149903</a> for this issue.</div><br/>

**Comment by muratugureminoglu** [comment]
<div>Agent Mohit Dubey unlinked Freshdesk ticket <a href="https://antmedia.freshdesk.com/a/tickets/149903">149903</a> from this issue.</div>
