### ISSUE TITLE
Preparing a Demo to create visibility for Analytics Logs

### ISSUE THREAD

**Issue by akiziltoprak** [ant-media/Ant-Media-Server#6379]
We need to prepare a Demo to upload the analytics log file to present a monitoring / stats viewing capability

**Comment by mekya** [comment]
Hi @muratugureminoglu,

Let me give you some more information about the context and how to proceed. 

- We write analytical logs to a file currently as json. It's available in `log/ant-media-server-analytics.log`
- The goal is to send these json data to an endpoint that we have a monitoring system for these analytics, as we do in server monitoring with grafana.
- There is one difference in here: we don't need to setup kafka, logstash, grafana at this time. In order to speed up the process, we send these information to [splunk](https://splunk.com/), [new reliec](https://newrelic.com/) or similar platform.
- This the [line that is the pattern of the messages](https://github.com/ant-media/Ant-Media-Server/blob/master/src/main/server/conf/logback.xml#L46) being written analytic log file
- At this issue, you can send the json analytic logs to an endpoint basically with some linux commands.
- The logs are [modeled here if you need](https://github.com/ant-media/Ant-Media-Server/tree/master/src/main/java/io/antmedia/analytic/model) 

My expectation for this task is to show the total number of viewers in the system. This is the [ViewerCountEvent](https://github.com/ant-media/Ant-Media-Server/blob/master/src/main/java/io/antmedia/analytic/model/ViewerCountEvent.java) to be sent as json.
For the later weeks, we'll show more things.

Let me know if I miss anything or you have any questions

Cheers
