### ISSUE TITLE
How to destroy the adaptor in react native

### ISSUE THREAD

**Issue by vincemavill** [ant-media/Ant-Media-Server#6399]
How can i destroy the adaptor Ant media, because the
pong command still showing on the logs and green dot doesn't disappear on the top right corner, even though I trigger the adaptor.stop(stream_id) and navigate back to other screen.

**Comment by vincemavill** [comment]
@mustafaboleken hope you can help sir, thank you

**Comment by mekya** [comment]
Hi @vincemavill,
Thank you for raising the issue and your patience. I'm putting this in the backlog. I'll try to schedule this week if we have some bandwidth. 


Cheers
Oguz

**Comment by vincemavill** [comment]
@mekya any updates with this? thank you

**Comment by mustafaboleken** [comment]
Hi @vincemavill,

I just got back from the vacation. Preparing the guide, I will share it with you today.

**Comment by mustafaboleken** [comment]
Hi @vincemavill,

It's ready to test. You can use the published sample. Btw, due to not making a breaking change,  I added extra functions to closing the local stream and WebSocket, reinitialing WebSocket, and some extra callbacks. Please let me know if this approach works for you.

https://github.com/ant-media/WebRTC-React-Native-SDK/pull/23

**Comment by Jastc** [comment]
Hi @mustafaboleken, I happened to have the same issue with the adaptor and the changes fixes it!

I only have one small issue; When you stop the stream and want start the stream again, you have to call the function/callback which calls `adaptor.publish(streamNameRef.current)` (in case of the example code the `handlePublish`) twice, instead of the expected single press, in order to stream again.. 

Is there a way around this or is an additional adjustment needed in order to fix this?

**Comment by mustafaboleken** [comment]
Hi @Jastc 

Let me update the sample. So, you don't need to double-click on it.

**Comment by mustafaboleken** [comment]
I updated the sample. You can check it again.

**Comment by Jastc** [comment]
Hi @mustafaboleken, I'm not sure if you get a notification of it or not, but I added some comments to the changes you've made in the example code -> [ant-media/WebRTC-React-Native-SDK#23](https://github.com/ant-media/WebRTC-React-Native-SDK/pull/23)

**Comment by mekya** [comment]
I've moved it to "In Progress" again to follow up closely in the sprint meeting. 

Thank you @Jastc

**Comment by mustafaboleken** [comment]
Hi @Jastc 

For some reason I missed the notification, thanks for remind from here, I will check it.
