### ISSUE TITLE
 Multiple streams stopped generating new .ts files on the server

### ISSUE THREAD

**Issue by amarantmeida** [ant-media/Ant-Media-Server#6486]
### Short description
Observed that several streams stopped generating new .ts files on the server. The .m3u8 files have remained unchanged for over 16 hours. 

In the antmedia-error.log file, we found the following error repeated approximately 62,137,440 times, causing the log file to grow to around 8GB:
`Error: [hls @ 0x7f4470079f40] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 193273527510 >= 12606721920`

Temp fix- Restarting the stream. 

### Environment

* Operating system and version:
* Java version: 
* Ant Media Server version: 
* Browser name and version:

### Steps to reproduce
1. NA

### Expected behavior
__Stream should not stop generating .ts files__

### Actual behavior
__several streams stopped generating new .ts files on the server. The .m3u8 files have remained unchanged for over 16 hours. __

 
### Logs
__(https://drive.google.com/drive/folders/1TbL80vblMyNZXy02MCD1cgdT6Lzpzk5R)__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by oleul05** [comment]
@amarantmeida, @burak-58 
We have 10 camera streams running on the same server. We noticed that when the ts file number for any camera stream reaches 1073740, it stops generating new ts files. Other camera stream which didn't reach 1073740 it wasn't stopped generating new ts files.

![image](https://github.com/user-attachments/assets/a0b40d62-bd66-48ad-920b-f4067997cbbd)

**Comment by mekya** [comment]
Hi @oleul05,

Thank you for the insight. It helped a lot to get basic understanding. My point is that it's likely overflowing the timestamps. 

1073740 * 2000(assumption of key frame interval in milliseconds) = 2147480000. 
It's close to half of integer limit(4294967296/2 = 2147483648). It overflows after 2147483648 because it's a signed value. 

We can check if this problem happens due to the Ant Media Server.

Cheers
Oguz

**Comment by oleul05** [comment]
@mekya Good afternoon.
Thank you for your investigation. Do you think the issue might be due to a problem on the camera or encoder side?

**Comment by lastpeony** [comment]
@oleul05 Is this happening with all cameras or some particular cameras?

**Comment by oleul05** [comment]
@lastpeony Yes, all the encoder are the same model.

**Comment by oleul05** [comment]
@burak-58, @lastpeony Are there any updates for this bug?
@burak-58, were you able toschedule a meeting which you mentioned yesterday on AMS tech talk meeting?

**Comment by lastpeony** [comment]
@oleul05 Hi ole i sent you a test server ip through e mails at the beginning of the week for us to debug this issue further. Could you please check your e mails/tickets?

**Comment by oleul05** [comment]
@lastpeony The issue was occurred in production environment and client was streaming from encoder. So is it really difficult for us to stream from those encoders. Could you please investigate from the log files or try to reproduce the same error from your side?
We will also try to reproduce this same error from our side with some other camera/encoder. If we succeed to reproduce the issue in our dev or QA environment we will let you know.

**Comment by oleul05** [comment]
@lastpeony, @burak-58 
We have observed the same error in the QA environment:
`Application provided invalid, non-monotonically increasing DTS to muxer in stream 1: 4374767250 >= 4374757710.`
However, after disabling the camera audio, this error no longer appears.
