### ISSUE TITLE
newtTrackAvailable triggers with wrong trackId on 2.10 (but not on 2.9)

### ISSUE THREAD

**Issue by MaZZly** [ant-media/Ant-Media-Server#6634]
### Short description

On ANT media 2.9 server, the same code works fine, but on ANT media 2.10 this problem happens.

When client1 opens a multitrack conference room and starts publishing as `caller_<roomId>` the other room participants get a `newTrackAvailable` where `trackId` is set to `ARDAMSvvideoTrack0` (should be `ARDAMSvcaller_<roomId>`)

### Environment

* Ant Media Server version: 2.10

### Steps to reproduce
1. Publish a stream to multitrack conference room with a specific id

### Expected behavior
`newTrackAvailable` to trigger with correct `trackId` set

### Actual behavior
`newTrackAvailable`  triggers with `trackId: "ARDAMSvvideoTrack0"`

**Comment by MaZZly** [comment]
@mustafaboleken @mekya, is this a known problem with 2.10, or some configuration error on our side?

**Comment by MaZZly** [comment]
@mustafaboleken @mekya we have now tried also with `2.10.1` and `2.11.0`  which have the same problem.

Rolling back to 2.9 solves the problem, so we will then just have to use that version until you guys have a fixed version available.

**Comment by MaZZly** [comment]
@burak-58 @mustafaboleken  **This should probably be documented somewhere and not just change like that without any notice in e.g. changelogs**...

Questions (and concerns) regarding this change:
1. Do we need to enable `dataChannel` for this functionality to work? (I'm guessing yes)
2. Is there any guarantee that `VIDEO_TRACK_ASSIGNMENT_LIST` will **always** trigger before the `newTrackAvailable` event? (Not just in the "happy cases")
   - If data channel message is received after the newTrackAvailable, we won't have the needed mapping... (i.e. resulting in an ERROR, or needing a hacky workaround solution on our end to "retry" until there is a mapping available...)
3. Could the "actual streamId" be readded (different naming is fine) to the `newTrackAvailable` event (so we don't need to rely on async data channel which might break in non-happy network cases...)

**Comment by burak-58** [comment]
Hi @MaZZly,
You are totally right with missing documentations. We should infor the users for such a change. 

1. Yes
2. It is not guaranteed. So you may use the workaround solution you wrote. Also there is such `requestVideoTrackAssignments(streamId)` method in WebRTC Adaptor that you can use to query under controll. 
3. Writing streamId somewhere in the track structure (which is defined in WebRTC source base) is really a hacky way and we cannot guarantee that all browsers support it. Actually I tried it in the past and had issue with different browsers.
In previous versions we used to use trackId field, but with the new implementation any track may be shared among different streams so we don't set track id with any stream id. Because the stream that is assigned to that track may be changed after created. (if you limit the track count)

**Comment by MaZZly** [comment]
Okay, fair enough :)
