### ISSUE TITLE
SRT URL customization

### ISSUE THREAD

**Issue by filip-ams** [ant-media/Ant-Media-Server#6840]
**Describe the solution you'd like**
The stream ID #!::u=WebRTCAppEE/test should be parsed correctly and matched to the corresponding application and stream in Ant Media Server. This enhancement would ensure compatibility with hardware encoders and avoid stream rejection errors.

**Additional context**
Current error message in Ant Media Server:

ERROR i.a.enterprise.srt.SRTAdaptor - There is no scope for incoming stream id. Parsed scope: #!::u=WebRTCAppEE, stream id: test original srt stream id:#!::u=WebRTCAppEE/test,bmd_uuid=a6892212-a71c-4c03-a91e-3b7c208c7fa4,bmd_name=NHRL-Y-BZ-Program-Feed

**Comment by lastpeony** [comment]
https://gitlab.com/Ant-Media/Ant-Media-Enterprise/-/merge_requests/761

No integration test added because i think unit is sufficient, if required i can add quickly.


Now server will parse streamId correctly from such command:

Correct me if this is sufficient for the requirement. @filip-ams 
`ffmpeg -re -i test.mp4 -vcodec libx264 -profile:v baseline -g 60 -acodec aac -f mpegts srt://172.17.52.70:4200?streamid=#!::u=LiveApp/stream1`

**Comment by amcchord** [comment]
yeah that should work assuming anything added after a ',' is also ignored!

**Comment by mekya** [comment]
Hi @amcchord,

Yes, it parses the incoming things with comma-separated way.  I'm currently working on this issue to merge it into the master

Cheers
Oguz

**Comment by mekya** [comment]
Hi @amcchord 
I've added you on linkedin.  Let's have a meeting to discuss what we can do together in a win-win way or what we can help you for your success. Keep in touch on linkedin.

Cheers
Oguz
