### ISSUE TITLE
WebRTC demo not working

### ISSUE THREAD

**Issue by mrcatman** [ant-media/Ant-Media-Server#8]
### Short description
I tried to check a WebRTC to RTMP demo, but probably the server can't see my stream. Neither the player at /WebRTCApp/player.html, not RTMP stream can't open, and the video recording size is 0KB.
I can see the image from my webcam locally, though.

Firstly I thought that I could be behind NAT, but the server works only locally on my PC and that is not probably the reason.

The log: https://pastebin.com/JAhhVQsL

### Environment

[] Operating system and version: Win10 X64
[] Browser: Chrome/61.0.3163.100 
[] Java version: JDK 9

**Comment by mekya** [comment]
Sorry for late reply,

This issue is generally about setting OS path variable. 

Are you sure you add ant-media-server/lib/native path to OS path variable?

Secondly, in windows platform if server is running on D and there is a space in the path of the directory, java behaves weirdly. Make sure there is no space in the absolute path of the folder where you extract files. 

Thirdly, I can give you instant support on this because WebRTC feature is important for us. I can share my whatsapp number. If you wish just send an email to mekya@antmedia.io

**Comment by mekya** [comment]
Closing this issue for the inactivity.
