### ISSUE TITLE
SFU MP4Muxing rotation

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#825]
here is an issue with sfu mp4muxing. When going live from ios or android
sdk. The recorded video of the webrtc stream is horizontal.
Whereas the stream was published in potrait mode from mobile

**Comment by igor-radivojevic-ct** [comment]
Hey guys, I just wanted to check why this issue is closed as I have experienced it myself, too.

Use case:
* Go to example app to stream from iPhone SE (iOS 13.3.1, Safari)
* Start publishing
* Go to https://mydomain.com/#/applications/WebRTCAppEE (Dashboard)
* Click play to watch the stream everything is fine, but keep in mind that this is using WebRTC  to watch that live stream
* Install this extension https://chrome.google.com/webstore/detail/native-hls-playback/emnphkkblegpebimobpbekeedfgemhof
* Now go to https://mydomain.com/WebRTCAppEE/streams/stream1.m3u8
* You will see that the stream is rotated horizontally but it should be in portrait mode as I'm publishing in portrait mode with my front camera. And the stream is fetched though HLS not WebRTC

Hope for the answer, and thank you :smile:

**Comment by salsaweb** [comment]
Hey @mekya @burak-58 we  are facing same issue for Android App and also for web examples.

**Steps to reproduce the behaviour:**
1. open in iPhone browser (safari, chrome) https://mydomain.com/WebRTCAppEE/ and publish broadcast
2. open in laptop browser https://mydomain.com/WebRTCAppEE/play.html?name=stream1&playOrder=hls it's important to set playOrder to HLS
3. as a result you will see video in rotation

we are using **Enterprise Edition 2.2.1 20201029_2042**

**Comment by mekya** [comment]
Thank you @salsaweb for letting us know :)

Let's discuss this issue on the following thread
https://github.com/ant-media/Ant-Media-Server/issues/3614
