### ISSUE TITLE
how can we run the antmedia server on https 

### ISSUE THREAD

**Issue by beyhangl** [ant-media/Ant-Media-Server#827]
# Issue

### Short description
__Brief description of what happened__

### Environment

* Operating system and version:
* Java version: openjdk version "1.8.0_191"
* Ant Media Server version:ant-media-server-1.6.1-community-1.6.1-190108_1656.zip
* Browser name and version:Chrome

My server has ssl cerficate and 443 port is open for https connections.

When i write like https://my-server-ip  i can see the apache2 screen.
After that i'm trying to run antmeadia but i can't reach via https or http.

For example:

http://server-ip:5080/WebRTCApp/
https://server-ip:5443/WebRTCApp/
https://server-ip:443/WebRTCApp/

3 of them not working and i can't reach . Before i tried not secure server, i can connect via http but https is not working.

[### Logs
INFO: Starting ProtocolHandler [http-nio2-0.0.0.0-5080]
[INFO] [main] org.apache.coyote.http11.Http11Nio2Protocol - Starting ProtocolHandler [http-nio2-0.0.0.0-5080]]

**Comment by SelimEmre** [comment]
Hi @beyhangl,
Thank you for your interest. Please check this documentation >> https://github.com/ant-media/Ant-Media-Server/wiki/How-to-Enable-SSL-for-Ant-Media-Server-%3F#enabling-ssl-in-linuxubuntu 
If you have any problem, please re-open this issue.

**Comment by mikegk** [comment]
Hi @SelimEmre ,
that does not solve the problem, as I understand him right he wants to have SSL-Certification for IP-Addresses. Let's encrypt doesn't support that ( https://community.letsencrypt.org/t/certificate-for-public-ip-without-domain-name/6082 ).

I ran into the same problem because I want to use the IP-Address to be called without any domain names. I also have no solution for that problem right now: https://stackoverflow.com/questions/55993357/ant-media-server-ssl-without-domain .

Best regards

**Comment by SelimEmre** [comment]
Hi @mikegk,

Yes, you are right. It is my fault. Btw, you can use the free domain and you can use SSL. Please check this URL: https://www.freenom.com/en/freeandpaiddomains.html Also, we provide subdomain to our customers like that: {subdomain-name}.antmedia.io.

Thanks,
Selim
