### ISSUE TITLE
Provide option for license in order to run in AWS or Azure Marketplaces seamlessly

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#886]

**Comment by davutcavdar** [comment]
Alternatives that worked on in order to run in AWS or Azure Marketplaces seamlessly:

- Created a script to replace a different red5.xml that does not include license bean creation (it is open to user intervention)

-Defined a setting to red5.properties such as isMarketEdition then check this before license control (it is open to user intervention)

-Define a license in firebase for the market version with no end date
